modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="iter_rpg"
version="0.7.0"
displayName="Iter RPG"
displayURL="https://www.curseforge.com/minecraft/mc-mods/iter-rpg"
logoFile="logo.png"
credits="https://discord.gg/veQH6zZfDb"
authors="BaronFonShish, RayRindou"
description="Global semi-vanilla RPG mod"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.iter_rpg]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"


[[dependencies.iter_rpg]]
    modId="curios_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.iter_rpg]]
    modId="bettercombat"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.iter_rpg]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.iter_rpg]]
    modId="playeranimator"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.iter_rpg]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.iter_rpg]]
    modId="cloth-config"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

