
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.thirdlife.iterrpg.init;

import net.thirdlife.iterrpg.procedures.GetPullingValueProcedure;
import net.thirdlife.iterrpg.procedures.BloodbranchProvideValueProcedure;
import net.thirdlife.iterrpg.item.WoodenSpearItem;
import net.thirdlife.iterrpg.item.WoodenScytheItem;
import net.thirdlife.iterrpg.item.WoodenFlailItem;
import net.thirdlife.iterrpg.item.WoddenDaggerItem;
import net.thirdlife.iterrpg.item.WaterSwordItem;
import net.thirdlife.iterrpg.item.WaterSpearItem;
import net.thirdlife.iterrpg.item.WaterShovelItem;
import net.thirdlife.iterrpg.item.WaterScytheItem;
import net.thirdlife.iterrpg.item.WaterRuneItem;
import net.thirdlife.iterrpg.item.WaterPickaxeItem;
import net.thirdlife.iterrpg.item.WaterIngotItem;
import net.thirdlife.iterrpg.item.WaterHoeItem;
import net.thirdlife.iterrpg.item.WaterFragmentItem;
import net.thirdlife.iterrpg.item.WaterFlailItem;
import net.thirdlife.iterrpg.item.WaterDaggerItem;
import net.thirdlife.iterrpg.item.WaterAxeItem;
import net.thirdlife.iterrpg.item.WaterArmorItem;
import net.thirdlife.iterrpg.item.WarpedGooItem;
import net.thirdlife.iterrpg.item.VolatileFireballLauncherItem;
import net.thirdlife.iterrpg.item.VoidSwordItem;
import net.thirdlife.iterrpg.item.VoidSpearItem;
import net.thirdlife.iterrpg.item.VoidShovelItem;
import net.thirdlife.iterrpg.item.VoidScytheItem;
import net.thirdlife.iterrpg.item.VoidRuneItem;
import net.thirdlife.iterrpg.item.VoidPickaxeItem;
import net.thirdlife.iterrpg.item.VoidIngotItem;
import net.thirdlife.iterrpg.item.VoidHoeItem;
import net.thirdlife.iterrpg.item.VoidFragmentItem;
import net.thirdlife.iterrpg.item.VoidFlailItem;
import net.thirdlife.iterrpg.item.VoidDaggerItem;
import net.thirdlife.iterrpg.item.VoidAxeItem;
import net.thirdlife.iterrpg.item.VoidArmorItem;
import net.thirdlife.iterrpg.item.VileTissueItem;
import net.thirdlife.iterrpg.item.VeryGoodAndCheerfulRapierItem;
import net.thirdlife.iterrpg.item.UnidentifiedSpellItem;
import net.thirdlife.iterrpg.item.TwiffleLumpItem;
import net.thirdlife.iterrpg.item.TormentorItem;
import net.thirdlife.iterrpg.item.TombstoneFragmentItem;
import net.thirdlife.iterrpg.item.ThunderclapItem;
import net.thirdlife.iterrpg.item.TheRockItem;
import net.thirdlife.iterrpg.item.SwordOfBoundingItem;
import net.thirdlife.iterrpg.item.StormcallerItem;
import net.thirdlife.iterrpg.item.StoneSpearItem;
import net.thirdlife.iterrpg.item.StoneScytheItem;
import net.thirdlife.iterrpg.item.StoneGeodeItem;
import net.thirdlife.iterrpg.item.StoneFlailItem;
import net.thirdlife.iterrpg.item.StoneDaggerItem;
import net.thirdlife.iterrpg.item.StingerItem;
import net.thirdlife.iterrpg.item.StarlessnessItem;
import net.thirdlife.iterrpg.item.StarfishItem;
import net.thirdlife.iterrpg.item.StardustIceItem;
import net.thirdlife.iterrpg.item.SpiderSilkItem;
import net.thirdlife.iterrpg.item.SpiderMeadMugItem;
import net.thirdlife.iterrpg.item.SpellZapItem;
import net.thirdlife.iterrpg.item.SpellVoidbeamItem;
import net.thirdlife.iterrpg.item.SpellSplashesItem;
import net.thirdlife.iterrpg.item.SpellShadelashItem;
import net.thirdlife.iterrpg.item.SpellScribblesItem;
import net.thirdlife.iterrpg.item.SpellRecallItem;
import net.thirdlife.iterrpg.item.SpellPoisonGasItem;
import net.thirdlife.iterrpg.item.SpellMendItem;
import net.thirdlife.iterrpg.item.SpellIgniteItem;
import net.thirdlife.iterrpg.item.SpellHealItem;
import net.thirdlife.iterrpg.item.SpellGustItem;
import net.thirdlife.iterrpg.item.SpellFrostSpikeItem;
import net.thirdlife.iterrpg.item.SpellFlameboltItem;
import net.thirdlife.iterrpg.item.SpellEtherboltItem;
import net.thirdlife.iterrpg.item.SpellEtherblastItem;
import net.thirdlife.iterrpg.item.SpellEmbersItem;
import net.thirdlife.iterrpg.item.SpellDropletsItem;
import net.thirdlife.iterrpg.item.SpellCultivateItem;
import net.thirdlife.iterrpg.item.SpellBookItem;
import net.thirdlife.iterrpg.item.SpellAttractItem;
import net.thirdlife.iterrpg.item.SpawnerFragmentItem;
import net.thirdlife.iterrpg.item.SolsticeItem;
import net.thirdlife.iterrpg.item.SmolderingTomeItem;
import net.thirdlife.iterrpg.item.SevenSeasConcoctionItem;
import net.thirdlife.iterrpg.item.SeashellItem;
import net.thirdlife.iterrpg.item.SanguarnetItem;
import net.thirdlife.iterrpg.item.SacredTwigItem;
import net.thirdlife.iterrpg.item.RuneOfChaosItem;
import net.thirdlife.iterrpg.item.RingMouldItem;
import net.thirdlife.iterrpg.item.RecurveBowItem;
import net.thirdlife.iterrpg.item.RaggedItem;
import net.thirdlife.iterrpg.item.ProfaneFleshItem;
import net.thirdlife.iterrpg.item.PrimordialIngotItem;
import net.thirdlife.iterrpg.item.PrimordialFragmentItem;
import net.thirdlife.iterrpg.item.PotsherdItem;
import net.thirdlife.iterrpg.item.PearlWandItem;
import net.thirdlife.iterrpg.item.PearlItem;
import net.thirdlife.iterrpg.item.OtherwordlyIngotItem;
import net.thirdlife.iterrpg.item.NimbleCopperShortstaffItem;
import net.thirdlife.iterrpg.item.NetherrackGeodeItem;
import net.thirdlife.iterrpg.item.NetheriteSpearItem;
import net.thirdlife.iterrpg.item.NetheriteScytheItem;
import net.thirdlife.iterrpg.item.NetheriteRingSanguarnetItem;
import net.thirdlife.iterrpg.item.NetheriteRingMagmanumItem;
import net.thirdlife.iterrpg.item.NetheriteRingItem;
import net.thirdlife.iterrpg.item.NetheriteRingEmeraldItem;
import net.thirdlife.iterrpg.item.NetheriteRingDiamondItem;
import net.thirdlife.iterrpg.item.NetheriteRingAmethystItem;
import net.thirdlife.iterrpg.item.NetheriteRingAbyssquartzItem;
import net.thirdlife.iterrpg.item.NetheriteFlailItem;
import net.thirdlife.iterrpg.item.NetheriteDaggerItem;
import net.thirdlife.iterrpg.item.MugItem;
import net.thirdlife.iterrpg.item.MobPlacerItem;
import net.thirdlife.iterrpg.item.MarrowItem;
import net.thirdlife.iterrpg.item.MagmanumSwordItem;
import net.thirdlife.iterrpg.item.MagmanumStaffItem;
import net.thirdlife.iterrpg.item.MagmanumPickaxeItem;
import net.thirdlife.iterrpg.item.MagmanumChunkItem;
import net.thirdlife.iterrpg.item.MagmanumArmorItem;
import net.thirdlife.iterrpg.item.IronSpearItem;
import net.thirdlife.iterrpg.item.IronScytheItem;
import net.thirdlife.iterrpg.item.IronRingSanguarnetItem;
import net.thirdlife.iterrpg.item.IronRingMagmanumItem;
import net.thirdlife.iterrpg.item.IronRingItem;
import net.thirdlife.iterrpg.item.IronRingEmeraldItem;
import net.thirdlife.iterrpg.item.IronRingDiamondItem;
import net.thirdlife.iterrpg.item.IronRingAmethystItem;
import net.thirdlife.iterrpg.item.IronRingAbyssquartzItem;
import net.thirdlife.iterrpg.item.IronFlailItem;
import net.thirdlife.iterrpg.item.IronDaggerItem;
import net.thirdlife.iterrpg.item.InkBottleItem;
import net.thirdlife.iterrpg.item.HydraStaffItem;
import net.thirdlife.iterrpg.item.HumieButcherItem;
import net.thirdlife.iterrpg.item.HollowVisageItem;
import net.thirdlife.iterrpg.item.HauntedSplinterItem;
import net.thirdlife.iterrpg.item.HarvestItem;
import net.thirdlife.iterrpg.item.GrimstonePebbleItem;
import net.thirdlife.iterrpg.item.GoldenSpearItem;
import net.thirdlife.iterrpg.item.GoldenScytheItem;
import net.thirdlife.iterrpg.item.GoldenFlailItem;
import net.thirdlife.iterrpg.item.GoldenDaggerItem;
import net.thirdlife.iterrpg.item.GoldRingSanguarnetItem;
import net.thirdlife.iterrpg.item.GoldRingMagmanumItem;
import net.thirdlife.iterrpg.item.GoldRingItem;
import net.thirdlife.iterrpg.item.GoldRingEmeraldItem;
import net.thirdlife.iterrpg.item.GoldRingDiamondItem;
import net.thirdlife.iterrpg.item.GoldRingAmethystItem;
import net.thirdlife.iterrpg.item.GoldRingAbyssquartzItem;
import net.thirdlife.iterrpg.item.GobsteelScrapItem;
import net.thirdlife.iterrpg.item.GobsteelJavelinItem;
import net.thirdlife.iterrpg.item.GistItem;
import net.thirdlife.iterrpg.item.GiantWeeperTearItem;
import net.thirdlife.iterrpg.item.FlawlessMagmanumItem;
import net.thirdlife.iterrpg.item.FlawlessEmeraldItem;
import net.thirdlife.iterrpg.item.FlawlessDiamondItem;
import net.thirdlife.iterrpg.item.FirestarterItem;
import net.thirdlife.iterrpg.item.FireSwordItem;
import net.thirdlife.iterrpg.item.FireSpearItem;
import net.thirdlife.iterrpg.item.FireShovelItem;
import net.thirdlife.iterrpg.item.FireScytheItem;
import net.thirdlife.iterrpg.item.FireRuneItem;
import net.thirdlife.iterrpg.item.FirePickaxeItem;
import net.thirdlife.iterrpg.item.FireIngotItem;
import net.thirdlife.iterrpg.item.FireHoeItem;
import net.thirdlife.iterrpg.item.FireFragmentItem;
import net.thirdlife.iterrpg.item.FireFlailItem;
import net.thirdlife.iterrpg.item.FireDaggerItem;
import net.thirdlife.iterrpg.item.FireAxeItem;
import net.thirdlife.iterrpg.item.FireArmorItem;
import net.thirdlife.iterrpg.item.FesteringWingsItem;
import net.thirdlife.iterrpg.item.EtherbrewItem;
import net.thirdlife.iterrpg.item.EtherbloomDecoctionItem;
import net.thirdlife.iterrpg.item.EternalTorrentItem;
import net.thirdlife.iterrpg.item.EssenceOfCreationItem;
import net.thirdlife.iterrpg.item.EndstoneGeodeItem;
import net.thirdlife.iterrpg.item.EnchantomeItem;
import net.thirdlife.iterrpg.item.EnchantedPageItem;
import net.thirdlife.iterrpg.item.EmptyRuneItem;
import net.thirdlife.iterrpg.item.ElementalUpgradeItem;
import net.thirdlife.iterrpg.item.ElementalSwordItem;
import net.thirdlife.iterrpg.item.ElementalArmorItem;
import net.thirdlife.iterrpg.item.EctoplasmItem;
import net.thirdlife.iterrpg.item.EarthSwordItem;
import net.thirdlife.iterrpg.item.EarthSpearItem;
import net.thirdlife.iterrpg.item.EarthShovelItem;
import net.thirdlife.iterrpg.item.EarthScytheItem;
import net.thirdlife.iterrpg.item.EarthRuneItem;
import net.thirdlife.iterrpg.item.EarthPickaxeItem;
import net.thirdlife.iterrpg.item.EarthIngotItem;
import net.thirdlife.iterrpg.item.EarthHoeItem;
import net.thirdlife.iterrpg.item.EarthFragmentItem;
import net.thirdlife.iterrpg.item.EarthFlailItem;
import net.thirdlife.iterrpg.item.EarthDaggerItem;
import net.thirdlife.iterrpg.item.EarthAxeItem;
import net.thirdlife.iterrpg.item.EarthArmorItem;
import net.thirdlife.iterrpg.item.DwarvenComponentsItem;
import net.thirdlife.iterrpg.item.DriftbowItem;
import net.thirdlife.iterrpg.item.DiamondSpearItem;
import net.thirdlife.iterrpg.item.DiamondScytheItem;
import net.thirdlife.iterrpg.item.DiamondFlailItem;
import net.thirdlife.iterrpg.item.DiamondDaggerItem;
import net.thirdlife.iterrpg.item.DemonboneItem;
import net.thirdlife.iterrpg.item.DemonboneFragmentsItem;
import net.thirdlife.iterrpg.item.DeepsteelSwordItem;
import net.thirdlife.iterrpg.item.DeepsteelPickaxeItem;
import net.thirdlife.iterrpg.item.DeepsteelIngotItem;
import net.thirdlife.iterrpg.item.DeepsteelAxeItem;
import net.thirdlife.iterrpg.item.DeepslateGeodeItem;
import net.thirdlife.iterrpg.item.DamnedItem;
import net.thirdlife.iterrpg.item.CrystalTearItem;
import net.thirdlife.iterrpg.item.CrescentItem;
import net.thirdlife.iterrpg.item.CoinPouchItem;
import net.thirdlife.iterrpg.item.CoinItem;
import net.thirdlife.iterrpg.item.CogHeartItem;
import net.thirdlife.iterrpg.item.CaltropItem;
import net.thirdlife.iterrpg.item.CalibratedLensItem;
import net.thirdlife.iterrpg.item.BowstringItem;
import net.thirdlife.iterrpg.item.BottleOfObsidianTearsItem;
import net.thirdlife.iterrpg.item.BoneWandItem;
import net.thirdlife.iterrpg.item.BonbItem;
import net.thirdlife.iterrpg.item.BloodthirstItem;
import net.thirdlife.iterrpg.item.BloodletterItem;
import net.thirdlife.iterrpg.item.BloodbranchItem;
import net.thirdlife.iterrpg.item.BloodBottleItem;
import net.thirdlife.iterrpg.item.BlackstoneGeodeItem;
import net.thirdlife.iterrpg.item.BeerMugItem;
import net.thirdlife.iterrpg.item.AzureItem;
import net.thirdlife.iterrpg.item.AxebeakMeatItem;
import net.thirdlife.iterrpg.item.AxebeakFeatherItem;
import net.thirdlife.iterrpg.item.AwakenedSanguarnetItem;
import net.thirdlife.iterrpg.item.ArcanePowderItem;
import net.thirdlife.iterrpg.item.ArcaneBouqueteItem;
import net.thirdlife.iterrpg.item.AncientKnowledgeItem;
import net.thirdlife.iterrpg.item.AmetrineSwordItem;
import net.thirdlife.iterrpg.item.AmetrineStaffItem;
import net.thirdlife.iterrpg.item.AmetrineSpearItem;
import net.thirdlife.iterrpg.item.AmetrineShovelItem;
import net.thirdlife.iterrpg.item.AmetrineScytheItem;
import net.thirdlife.iterrpg.item.AmetrinePickaxeItem;
import net.thirdlife.iterrpg.item.AmetrineNuggetItem;
import net.thirdlife.iterrpg.item.AmetrineItem;
import net.thirdlife.iterrpg.item.AmetrineIngotItem;
import net.thirdlife.iterrpg.item.AmetrineHoeItem;
import net.thirdlife.iterrpg.item.AmetrineFlailItem;
import net.thirdlife.iterrpg.item.AmetrineDaggerItem;
import net.thirdlife.iterrpg.item.AmetrineAxeItem;
import net.thirdlife.iterrpg.item.AmethystWandItem;
import net.thirdlife.iterrpg.item.AirSwordItem;
import net.thirdlife.iterrpg.item.AirSpearItem;
import net.thirdlife.iterrpg.item.AirShovelItem;
import net.thirdlife.iterrpg.item.AirScytheItem;
import net.thirdlife.iterrpg.item.AirRuneItem;
import net.thirdlife.iterrpg.item.AirPickaxeItem;
import net.thirdlife.iterrpg.item.AirIngotItem;
import net.thirdlife.iterrpg.item.AirHoeItem;
import net.thirdlife.iterrpg.item.AirFragmentItem;
import net.thirdlife.iterrpg.item.AirFlailItem;
import net.thirdlife.iterrpg.item.AirDaggerItem;
import net.thirdlife.iterrpg.item.AirAxeItem;
import net.thirdlife.iterrpg.item.AirArmorItem;
import net.thirdlife.iterrpg.item.AbyssquartzWandItem;
import net.thirdlife.iterrpg.item.AbyssquartzShardItem;
import net.thirdlife.iterrpg.item.AbstruseClothItem;
import net.thirdlife.iterrpg.block.display.FleshWeaverDisplayItem;
import net.thirdlife.iterrpg.IterRpgMod;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.common.ForgeSpawnEggItem;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.client.renderer.item.ItemProperties;

@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
public class IterRpgModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, IterRpgMod.MODID);
	public static final RegistryObject<Item> GRIMSTONE = block(IterRpgModBlocks.GRIMSTONE);
	public static final RegistryObject<Item> GRIMSTONE_BRICKS = block(IterRpgModBlocks.GRIMSTONE_BRICKS);
	public static final RegistryObject<Item> CRACKED_GRIMSTONE_BRICKS = block(IterRpgModBlocks.CRACKED_GRIMSTONE_BRICKS);
	public static final RegistryObject<Item> GRIMSTONE_BRICKS_SLAB = block(IterRpgModBlocks.GRIMSTONE_BRICKS_SLAB);
	public static final RegistryObject<Item> POLISHED_GRIMSTONE = block(IterRpgModBlocks.POLISHED_GRIMSTONE);
	public static final RegistryObject<Item> GRIMSTONE_SLAB = block(IterRpgModBlocks.GRIMSTONE_SLAB);
	public static final RegistryObject<Item> POLISHED_GRIMSTONE_SLAB = block(IterRpgModBlocks.POLISHED_GRIMSTONE_SLAB);
	public static final RegistryObject<Item> AMETRINE_INGOT = REGISTRY.register("ametrine_ingot", () -> new AmetrineIngotItem());
	public static final RegistryObject<Item> SPAWNER_FRAGMENT = REGISTRY.register("spawner_fragment", () -> new SpawnerFragmentItem());
	public static final RegistryObject<Item> COIN = REGISTRY.register("coin", () -> new CoinItem());
	public static final RegistryObject<Item> POLISHED_GRIMSTONE_STAIRS = block(IterRpgModBlocks.POLISHED_GRIMSTONE_STAIRS);
	public static final RegistryObject<Item> GRIMSTONE_BRICKS_STAIRS = block(IterRpgModBlocks.GRIMSTONE_BRICKS_STAIRS);
	public static final RegistryObject<Item> POLISHED_GRIMSTONE_WALL = block(IterRpgModBlocks.POLISHED_GRIMSTONE_WALL);
	public static final RegistryObject<Item> GRIMSTONE_BRICKS_WALL = block(IterRpgModBlocks.GRIMSTONE_BRICKS_WALL);
	public static final RegistryObject<Item> CHISELED_GRIMSTONE_BRICKS = block(IterRpgModBlocks.CHISELED_GRIMSTONE_BRICKS);
	public static final RegistryObject<Item> SMALL_VASE = block(IterRpgModBlocks.SMALL_VASE);
	public static final RegistryObject<Item> VASE = block(IterRpgModBlocks.VASE);
	public static final RegistryObject<Item> BIG_VASE = block(IterRpgModBlocks.BIG_VASE);
	public static final RegistryObject<Item> AMETRINE_BLOCK = block(IterRpgModBlocks.AMETRINE_BLOCK);
	public static final RegistryObject<Item> ETHERBLOOM = block(IterRpgModBlocks.ETHERBLOOM);
	public static final RegistryObject<Item> ARCANE_FLOWER_SEEDS = block(IterRpgModBlocks.ARCANE_FLOWER_SEEDS);
	public static final RegistryObject<Item> ETHER_DUST = REGISTRY.register("ether_dust", () -> new ArcanePowderItem());
	public static final RegistryObject<Item> WOODEN_FLAIL = REGISTRY.register("wooden_flail", () -> new WoodenFlailItem());
	public static final RegistryObject<Item> STONE_FLAIL = REGISTRY.register("stone_flail", () -> new StoneFlailItem());
	public static final RegistryObject<Item> IRON_FLAIL = REGISTRY.register("iron_flail", () -> new IronFlailItem());
	public static final RegistryObject<Item> GOLDEN_FLAIL = REGISTRY.register("golden_flail", () -> new GoldenFlailItem());
	public static final RegistryObject<Item> DIAMOND_FLAIL = REGISTRY.register("diamond_flail", () -> new DiamondFlailItem());
	public static final RegistryObject<Item> NETHERITE_FLAIL = REGISTRY.register("netherite_flail", () -> new NetheriteFlailItem());
	public static final RegistryObject<Item> WOODEN_SCYTHE = REGISTRY.register("wooden_scythe", () -> new WoodenScytheItem());
	public static final RegistryObject<Item> STONE_SCYTHE = REGISTRY.register("stone_scythe", () -> new StoneScytheItem());
	public static final RegistryObject<Item> IRON_SCYTHE = REGISTRY.register("iron_scythe", () -> new IronScytheItem());
	public static final RegistryObject<Item> GOLDEN_SCYTHE = REGISTRY.register("golden_scythe", () -> new GoldenScytheItem());
	public static final RegistryObject<Item> DIAMOND_SCYTHE = REGISTRY.register("diamond_scythe", () -> new DiamondScytheItem());
	public static final RegistryObject<Item> NETHERITE_SCYTHE = REGISTRY.register("netherite_scythe", () -> new NetheriteScytheItem());
	public static final RegistryObject<Item> GENERIC_DUNGEON_GEN_BLOCK = block(IterRpgModBlocks.GENERIC_DUNGEON_GEN_BLOCK);
	public static final RegistryObject<Item> GRIEVER_SPAWN_EGG = REGISTRY.register("griever_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.GRIEVER, -13686721, -15531998, new Item.Properties()));
	public static final RegistryObject<Item> MOURNSTONE_SPAWN_EGG = REGISTRY.register("mournstone_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.MOURNSTONE, -13686721, -1020441, new Item.Properties()));
	public static final RegistryObject<Item> MAGMANUM_CHUNK = REGISTRY.register("magmanum_chunk", () -> new MagmanumChunkItem());
	public static final RegistryObject<Item> MAGMANUM_ORE = block(IterRpgModBlocks.MAGMANUM_ORE);
	public static final RegistryObject<Item> GEODITE = block(IterRpgModBlocks.GEODITE);
	public static final RegistryObject<Item> BLACKSTONE_GEODITE = block(IterRpgModBlocks.BLACKSTONE_GEODITE);
	public static final RegistryObject<Item> EARTH_RUNE = REGISTRY.register("earth_rune", () -> new EarthRuneItem());
	public static final RegistryObject<Item> GOBLIN_WARRIOR_SPAWN_EGG = REGISTRY.register("goblin_warrior_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.GOBLIN_WARRIOR, -5392333, -7500906, new Item.Properties()));
	public static final RegistryObject<Item> WATER_RUNE = REGISTRY.register("water_rune", () -> new WaterRuneItem());
	public static final RegistryObject<Item> WATER_FRAGMENT = REGISTRY.register("water_fragment", () -> new WaterFragmentItem());
	public static final RegistryObject<Item> EMPTY_RUNE = REGISTRY.register("empty_rune", () -> new EmptyRuneItem());
	public static final RegistryObject<Item> FIRE_ELEMENTAL_SPAWN_EGG = REGISTRY.register("fire_elemental_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.FIRE_ELEMENTAL, -6213352, -1917878, new Item.Properties()));
	public static final RegistryObject<Item> EARTH_FRAGMENT = REGISTRY.register("earth_fragment", () -> new EarthFragmentItem());
	public static final RegistryObject<Item> BLOATED_SPAWN_EGG = REGISTRY.register("bloated_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.BLOATED, -11693440, -10100515, new Item.Properties()));
	public static final RegistryObject<Item> MAGMANUM_ARMOR_HELMET = REGISTRY.register("magmanum_armor_helmet", () -> new MagmanumArmorItem.Helmet());
	public static final RegistryObject<Item> MAGMANUM_ARMOR_CHESTPLATE = REGISTRY.register("magmanum_armor_chestplate", () -> new MagmanumArmorItem.Chestplate());
	public static final RegistryObject<Item> MAGMANUM_ARMOR_LEGGINGS = REGISTRY.register("magmanum_armor_leggings", () -> new MagmanumArmorItem.Leggings());
	public static final RegistryObject<Item> MAGMANUM_ARMOR_BOOTS = REGISTRY.register("magmanum_armor_boots", () -> new MagmanumArmorItem.Boots());
	public static final RegistryObject<Item> EARTH_ELEMENTAL_SPAWN_EGG = REGISTRY.register("earth_elemental_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.EARTH_ELEMENTAL, -10730928, -11030686, new Item.Properties()));
	public static final RegistryObject<Item> MAGMANUM_BLOCK = block(IterRpgModBlocks.MAGMANUM_BLOCK);
	public static final RegistryObject<Item> WEEPER_SPAWN_EGG = REGISTRY.register("weeper_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.WEEPER, -13686721, -14349255, new Item.Properties()));
	public static final RegistryObject<Item> CRYSTAL_TEAR = REGISTRY.register("crystal_tear", () -> new CrystalTearItem());
	public static final RegistryObject<Item> CHARGED_GRIMSTONE_BRICKS = block(IterRpgModBlocks.CHARGED_GRIMSTONE_BRICKS);
	public static final RegistryObject<Item> GRIM_KEYHOLE = block(IterRpgModBlocks.GRIM_KEYHOLE);
	public static final RegistryObject<Item> SORROWSEALED_SPAWN_EGG = REGISTRY.register("sorrowsealed_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.SORROWSEALED, -11580839, -1020441, new Item.Properties()));
	public static final RegistryObject<Item> SORROW_SPIRE_GEN_BLOCK = block(IterRpgModBlocks.SORROW_SPIRE_GEN_BLOCK);
	public static final RegistryObject<Item> WITCHMUD = block(IterRpgModBlocks.WITCHMUD);
	public static final RegistryObject<Item> CATTAIL = doubleBlock(IterRpgModBlocks.CATTAIL);
	public static final RegistryObject<Item> BLOODBRANCH = REGISTRY.register("bloodbranch", () -> new BloodbranchItem());
	public static final RegistryObject<Item> GIANT_CHAIN = block(IterRpgModBlocks.GIANT_CHAIN);
	public static final RegistryObject<Item> COMPACTED_SORROWSEALED = block(IterRpgModBlocks.COMPACTED_SORROWSEALED);
	public static final RegistryObject<Item> TORMENTOR = REGISTRY.register("tormentor", () -> new TormentorItem());
	public static final RegistryObject<Item> SCALLOP_SPAWN_EGG = REGISTRY.register("scallop_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.SCALLOP, -10134683, -2706222, new Item.Properties()));
	public static final RegistryObject<Item> GIANT_SPIDER_SPAWN_EGG = REGISTRY.register("giant_spider_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.GIANT_SPIDER, -12766183, -5763570, new Item.Properties()));
	public static final RegistryObject<Item> SPIDER_EGG = block(IterRpgModBlocks.SPIDER_EGG);
	public static final RegistryObject<Item> SPIDER_SILK = REGISTRY.register("spider_silk", () -> new SpiderSilkItem());
	public static final RegistryObject<Item> SPIDERLING_SPAWN_EGG = REGISTRY.register("spiderling_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.SPIDERLING, -2372425, -13029294, new Item.Properties()));
	public static final RegistryObject<Item> HIVESTONE = block(IterRpgModBlocks.HIVESTONE);
	public static final RegistryObject<Item> TWIFFLE = block(IterRpgModBlocks.TWIFFLE);
	public static final RegistryObject<Item> TWIFFLE_BLOCK = block(IterRpgModBlocks.TWIFFLE_BLOCK);
	public static final RegistryObject<Item> TWIFFLE_LUMP = REGISTRY.register("twiffle_lump", () -> new TwiffleLumpItem());
	public static final RegistryObject<Item> AIR_RUNE = REGISTRY.register("air_rune", () -> new AirRuneItem());
	public static final RegistryObject<Item> FIRE_RUNE = REGISTRY.register("fire_rune", () -> new FireRuneItem());
	public static final RegistryObject<Item> VOID_RUNE = REGISTRY.register("void_rune", () -> new VoidRuneItem());
	public static final RegistryObject<Item> AIR_FRAGMENT = REGISTRY.register("air_fragment", () -> new AirFragmentItem());
	public static final RegistryObject<Item> FIRE_FRAGMENT = REGISTRY.register("fire_fragment", () -> new FireFragmentItem());
	public static final RegistryObject<Item> CUT_HIVESTONE = block(IterRpgModBlocks.CUT_HIVESTONE);
	public static final RegistryObject<Item> CRACKED_HIVESTONE = block(IterRpgModBlocks.CRACKED_HIVESTONE);
	public static final RegistryObject<Item> CRUMBLING_HIVESTONE = block(IterRpgModBlocks.CRUMBLING_HIVESTONE);
	public static final RegistryObject<Item> RUNIC_HIVESTONE = block(IterRpgModBlocks.RUNIC_HIVESTONE);
	public static final RegistryObject<Item> SILKY_HIVESTONE = block(IterRpgModBlocks.SILKY_HIVESTONE);
	public static final RegistryObject<Item> WEAVED_HIVESTONE = block(IterRpgModBlocks.WEAVED_HIVESTONE);
	public static final RegistryObject<Item> INFESTED_HIVESTONE = block(IterRpgModBlocks.INFESTED_HIVESTONE);
	public static final RegistryObject<Item> HIVESTONE_SLAB = block(IterRpgModBlocks.HIVESTONE_SLAB);
	public static final RegistryObject<Item> HIVESTONE_STAIRS = block(IterRpgModBlocks.HIVESTONE_STAIRS);
	public static final RegistryObject<Item> HIVESTONE_WALL = block(IterRpgModBlocks.HIVESTONE_WALL);
	public static final RegistryObject<Item> VOID_FRAGMENT = REGISTRY.register("void_fragment", () -> new VoidFragmentItem());
	public static final RegistryObject<Item> STARFISH = REGISTRY.register("starfish", () -> new StarfishItem());
	public static final RegistryObject<Item> SEASHELL = REGISTRY.register("seashell", () -> new SeashellItem());
	public static final RegistryObject<Item> PEARL = REGISTRY.register("pearl", () -> new PearlItem());
	public static final RegistryObject<Item> CLOUD_BLOCK = block(IterRpgModBlocks.CLOUD_BLOCK);
	public static final RegistryObject<Item> SMALL_VASE_DECO = block(IterRpgModBlocks.SMALL_VASE_DECO);
	public static final RegistryObject<Item> VASE_DECO = block(IterRpgModBlocks.VASE_DECO);
	public static final RegistryObject<Item> BIG_VASE_DECO = block(IterRpgModBlocks.BIG_VASE_DECO);
	public static final RegistryObject<Item> POTSHERD = REGISTRY.register("potsherd", () -> new PotsherdItem());
	public static final RegistryObject<Item> MUDKIN_SPAWN_EGG = REGISTRY.register("mudkin_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.MUDKIN, -11060690, -11574471, new Item.Properties()));
	public static final RegistryObject<Item> HOBGOBLIN_SPAWN_EGG = REGISTRY.register("hobgoblin_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.HOBGOBLIN, -15633798, -13230801, new Item.Properties()));
	public static final RegistryObject<Item> GOBLIN_DUNGEON_GEN = block(IterRpgModBlocks.GOBLIN_DUNGEON_GEN);
	public static final RegistryObject<Item> GUNPOWDER_BARREL = block(IterRpgModBlocks.GUNPOWDER_BARREL);
	public static final RegistryObject<Item> ARTHROPOD_CATACOMBS_GEN_BLOCK = block(IterRpgModBlocks.ARTHROPOD_CATACOMBS_GEN_BLOCK);
	public static final RegistryObject<Item> PEEPER_SPAWN_EGG = REGISTRY.register("peeper_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.PEEPER, -12368305, -15592681, new Item.Properties()));
	public static final RegistryObject<Item> HOLLOW_VISAGE = REGISTRY.register("hollow_visage", () -> new HollowVisageItem());
	public static final RegistryObject<Item> DRILL = block(IterRpgModBlocks.DRILL);
	public static final RegistryObject<Item> STONE_GEODE = REGISTRY.register("stone_geode", () -> new StoneGeodeItem());
	public static final RegistryObject<Item> NETHERRACK_GEODE = REGISTRY.register("netherrack_geode", () -> new NetherrackGeodeItem());
	public static final RegistryObject<Item> BLACKSTONE_GEODE = REGISTRY.register("blackstone_geode", () -> new BlackstoneGeodeItem());
	public static final RegistryObject<Item> DEEPSLATE_GEODITE = block(IterRpgModBlocks.DEEPSLATE_GEODITE);
	public static final RegistryObject<Item> NETHERRACK_GEODITE = block(IterRpgModBlocks.NETHERRACK_GEODITE);
	public static final RegistryObject<Item> ENDSTONE_GEODITE = block(IterRpgModBlocks.ENDSTONE_GEODITE);
	public static final RegistryObject<Item> VOID_ELEMENTAL_SPAWN_EGG = REGISTRY.register("void_elemental_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.VOID_ELEMENTAL, -15462119, -34575, new Item.Properties()));
	public static final RegistryObject<Item> AIR_ELEMENTAL_SPAWN_EGG = REGISTRY.register("air_elemental_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.AIR_ELEMENTAL, -3542273, -1917878, new Item.Properties()));
	public static final RegistryObject<Item> WATER_ELEMENTAL_SPAWN_EGG = REGISTRY.register("water_elemental_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.WATER_ELEMENTAL, -9521193, -14795684, new Item.Properties()));
	public static final RegistryObject<Item> GOBLIN_SPAWN_EGG = REGISTRY.register("goblin_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.GOBLIN, -5392333, -9359322, new Item.Properties()));
	public static final RegistryObject<Item> CALTROP = REGISTRY.register("caltrop", () -> new CaltropItem());
	public static final RegistryObject<Item> SPIDER_SILK_BLOCK = block(IterRpgModBlocks.SPIDER_SILK_BLOCK);
	public static final RegistryObject<Item> INSATIABLE_SPAWN_EGG = REGISTRY.register("insatiable_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.INSATIABLE, -11107202, -11753854, new Item.Properties()));
	public static final RegistryObject<Item> AMETRINE_BRICKS = block(IterRpgModBlocks.AMETRINE_BRICKS);
	public static final RegistryObject<Item> SACRED_LOG = block(IterRpgModBlocks.SACRED_LOG);
	public static final RegistryObject<Item> SACRED_PLANKS = block(IterRpgModBlocks.SACRED_PLANKS);
	public static final RegistryObject<Item> SACRED_WOOD = block(IterRpgModBlocks.SACRED_WOOD);
	public static final RegistryObject<Item> SACRED_LEAVES = block(IterRpgModBlocks.SACRED_LEAVES);
	public static final RegistryObject<Item> SACRED_STAIRS = block(IterRpgModBlocks.SACRED_STAIRS);
	public static final RegistryObject<Item> SACRED_SLAB = block(IterRpgModBlocks.SACRED_SLAB);
	public static final RegistryObject<Item> SACRED_FENCE = block(IterRpgModBlocks.SACRED_FENCE);
	public static final RegistryObject<Item> SACRED_FENCE_GATE = block(IterRpgModBlocks.SACRED_FENCE_GATE);
	public static final RegistryObject<Item> SACRED_PRESSURE_PLATE = block(IterRpgModBlocks.SACRED_PRESSURE_PLATE);
	public static final RegistryObject<Item> SACRED_BUTTON = block(IterRpgModBlocks.SACRED_BUTTON);
	public static final RegistryObject<Item> SACRED_DOOR = doubleBlock(IterRpgModBlocks.SACRED_DOOR);
	public static final RegistryObject<Item> SACRED_TRAPDOOR = block(IterRpgModBlocks.SACRED_TRAPDOOR);
	public static final RegistryObject<Item> SACRED_TWIG = REGISTRY.register("sacred_twig", () -> new SacredTwigItem());
	public static final RegistryObject<Item> SACRED_SAPLING = block(IterRpgModBlocks.SACRED_SAPLING);
	public static final RegistryObject<Item> CRESCENT = REGISTRY.register("crescent", () -> new CrescentItem());
	public static final RegistryObject<Item> PEARL_BLOCK = block(IterRpgModBlocks.PEARL_BLOCK);
	public static final RegistryObject<Item> AMETRINE_NUGGET = REGISTRY.register("ametrine_nugget", () -> new AmetrineNuggetItem());
	public static final RegistryObject<Item> MAGMANUM_PICKAXE = REGISTRY.register("magmanum_pickaxe", () -> new MagmanumPickaxeItem());
	public static final RegistryObject<Item> GOBSTEEL_SCRAP = REGISTRY.register("gobsteel_scrap", () -> new GobsteelScrapItem());
	public static final RegistryObject<Item> MOB_PLACER = REGISTRY.register("mob_placer", () -> new MobPlacerItem());
	public static final RegistryObject<Item> GOBLIN_SPAWNER = block(IterRpgModBlocks.GOBLIN_SPAWNER);
	public static final RegistryObject<Item> ELEMENTAL_SWORD = REGISTRY.register("elemental_sword", () -> new ElementalSwordItem());
	public static final RegistryObject<Item> DEEPSLATE_GEODE = REGISTRY.register("deepslate_geode", () -> new DeepslateGeodeItem());
	public static final RegistryObject<Item> HUMIE_BUTCHER = REGISTRY.register("humie_butcher", () -> new HumieButcherItem());
	public static final RegistryObject<Item> MAGMANUM_SWORD = REGISTRY.register("magmanum_sword", () -> new MagmanumSwordItem());
	public static final RegistryObject<Item> VERY_GOOD_AND_CHEERFUL_RAPIER = REGISTRY.register("very_good_and_cheerful_rapier", () -> new VeryGoodAndCheerfulRapierItem());
	public static final RegistryObject<Item> ENDSTONE_GEODE = REGISTRY.register("endstone_geode", () -> new EndstoneGeodeItem());
	public static final RegistryObject<Item> BLOODTHIRST = REGISTRY.register("bloodthirst", () -> new BloodthirstItem());
	public static final RegistryObject<Item> EARTH_INGOT = REGISTRY.register("earth_ingot", () -> new EarthIngotItem());
	public static final RegistryObject<Item> WATER_INGOT = REGISTRY.register("water_ingot", () -> new WaterIngotItem());
	public static final RegistryObject<Item> AIR_INGOT = REGISTRY.register("air_ingot", () -> new AirIngotItem());
	public static final RegistryObject<Item> FIRE_INGOT = REGISTRY.register("fire_ingot", () -> new FireIngotItem());
	public static final RegistryObject<Item> VOID_INGOT = REGISTRY.register("void_ingot", () -> new VoidIngotItem());
	public static final RegistryObject<Item> ABYSS_QUARTZ = block(IterRpgModBlocks.ABYSS_QUARTZ);
	public static final RegistryObject<Item> ABYSSQUARTZ_SHARD = REGISTRY.register("abyssquartz_shard", () -> new AbyssquartzShardItem());
	public static final RegistryObject<Item> ABYSSQUARTZ_BLOCK = block(IterRpgModBlocks.ABYSSQUARTZ_BLOCK);
	public static final RegistryObject<Item> GRIM_SOULTRAP = block(IterRpgModBlocks.GRIM_SOULTRAP);
	public static final RegistryObject<Item> BARRIER_PROJECTOR = block(IterRpgModBlocks.BARRIER_PROJECTOR);
	public static final RegistryObject<Item> RUNIC_GRIMSTONE = block(IterRpgModBlocks.RUNIC_GRIMSTONE);
	public static final RegistryObject<Item> RUNIC_GRIMSTONE_ACTIVE = block(IterRpgModBlocks.RUNIC_GRIMSTONE_ACTIVE);
	public static final RegistryObject<Item> GIANT_PHANTOM_CHAIN = block(IterRpgModBlocks.GIANT_PHANTOM_CHAIN);
	public static final RegistryObject<Item> COIN_PILE = block(IterRpgModBlocks.COIN_PILE);
	public static final RegistryObject<Item> COIN_BLOCK = block(IterRpgModBlocks.COIN_BLOCK);
	public static final RegistryObject<Item> STINGER = REGISTRY.register("stinger", () -> new StingerItem());
	public static final RegistryObject<Item> GIANT_WEEPER_TEAR = REGISTRY.register("giant_weeper_tear", () -> new GiantWeeperTearItem());
	public static final RegistryObject<Item> MARROW = REGISTRY.register("marrow", () -> new MarrowItem());
	public static final RegistryObject<Item> GOBSTEEL_BLOCK = block(IterRpgModBlocks.GOBSTEEL_BLOCK);
	public static final RegistryObject<Item> HARVEST = REGISTRY.register("harvest", () -> new HarvestItem());
	public static final RegistryObject<Item> ETERNAL_TORRENT = REGISTRY.register("eternal_torrent", () -> new EternalTorrentItem());
	public static final RegistryObject<Item> STORMCALLER = REGISTRY.register("stormcaller", () -> new StormcallerItem());
	public static final RegistryObject<Item> SOLSTICE = REGISTRY.register("solstice", () -> new SolsticeItem());
	public static final RegistryObject<Item> STARLESSNESS = REGISTRY.register("starlessness", () -> new StarlessnessItem());
	public static final RegistryObject<Item> CALIBRATED_LENS = REGISTRY.register("calibrated_lens", () -> new CalibratedLensItem());
	public static final RegistryObject<Item> SPELL_BOOK = REGISTRY.register("spell_book", () -> new SpellBookItem());
	public static final RegistryObject<Item> DWARF_SPAWN_EGG = REGISTRY.register("dwarf_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.DWARF, -8098460, -5353678, new Item.Properties()));
	public static final RegistryObject<Item> MUG = REGISTRY.register("mug", () -> new MugItem());
	public static final RegistryObject<Item> BEER_MUG = REGISTRY.register("beer_mug", () -> new BeerMugItem());
	public static final RegistryObject<Item> SPIDER_MEAD_MUG = REGISTRY.register("spider_mead_mug", () -> new SpiderMeadMugItem());
	public static final RegistryObject<Item> DRIFTBOW = REGISTRY.register("driftbow", () -> new DriftbowItem());
	public static final RegistryObject<Item> SPELL_HEAL = REGISTRY.register("spell_heal", () -> new SpellHealItem());
	public static final RegistryObject<Item> RAGGED_HELMET = REGISTRY.register("ragged_helmet", () -> new RaggedItem.Helmet());
	public static final RegistryObject<Item> RAGGED_CHESTPLATE = REGISTRY.register("ragged_chestplate", () -> new RaggedItem.Chestplate());
	public static final RegistryObject<Item> RAGGED_LEGGINGS = REGISTRY.register("ragged_leggings", () -> new RaggedItem.Leggings());
	public static final RegistryObject<Item> RAGGED_BOOTS = REGISTRY.register("ragged_boots", () -> new RaggedItem.Boots());
	public static final RegistryObject<Item> ELEMENTAL_UPGRADE = REGISTRY.register("elemental_upgrade", () -> new ElementalUpgradeItem());
	public static final RegistryObject<Item> WOODEN_SPEAR = REGISTRY.register("wooden_spear", () -> new WoodenSpearItem());
	public static final RegistryObject<Item> STONE_SPEAR = REGISTRY.register("stone_spear", () -> new StoneSpearItem());
	public static final RegistryObject<Item> IRON_SPEAR = REGISTRY.register("iron_spear", () -> new IronSpearItem());
	public static final RegistryObject<Item> GOLDEN_SPEAR = REGISTRY.register("golden_spear", () -> new GoldenSpearItem());
	public static final RegistryObject<Item> DIAMOND_SPEAR = REGISTRY.register("diamond_spear", () -> new DiamondSpearItem());
	public static final RegistryObject<Item> NETHERITE_SPEAR = REGISTRY.register("netherite_spear", () -> new NetheriteSpearItem());
	public static final RegistryObject<Item> WODDEN_DAGGER = REGISTRY.register("wodden_dagger", () -> new WoddenDaggerItem());
	public static final RegistryObject<Item> STONE_DAGGER = REGISTRY.register("stone_dagger", () -> new StoneDaggerItem());
	public static final RegistryObject<Item> IRON_DAGGER = REGISTRY.register("iron_dagger", () -> new IronDaggerItem());
	public static final RegistryObject<Item> GOLDEN_DAGGER = REGISTRY.register("golden_dagger", () -> new GoldenDaggerItem());
	public static final RegistryObject<Item> DIAMOND_DAGGER = REGISTRY.register("diamond_dagger", () -> new DiamondDaggerItem());
	public static final RegistryObject<Item> NETHERITE_DAGGER = REGISTRY.register("netherite_dagger", () -> new NetheriteDaggerItem());
	public static final RegistryObject<Item> MONOLITH_STONE = block(IterRpgModBlocks.MONOLITH_STONE);
	public static final RegistryObject<Item> EARTH_SEAL = block(IterRpgModBlocks.EARTH_SEAL);
	public static final RegistryObject<Item> WATER_SEAL = block(IterRpgModBlocks.WATER_SEAL);
	public static final RegistryObject<Item> AIR_SEAL = block(IterRpgModBlocks.AIR_SEAL);
	public static final RegistryObject<Item> FIRE_SEAL = block(IterRpgModBlocks.FIRE_SEAL);
	public static final RegistryObject<Item> VOID_SEAL = block(IterRpgModBlocks.VOID_SEAL);
	public static final RegistryObject<Item> MONOLITH_STAIRS = block(IterRpgModBlocks.MONOLITH_STAIRS);
	public static final RegistryObject<Item> MONOLITH_SLAB = block(IterRpgModBlocks.MONOLITH_SLAB);
	public static final RegistryObject<Item> MONOLITH_WALL = block(IterRpgModBlocks.MONOLITH_WALL);
	public static final RegistryObject<Item> SPIRE_SPAWNER = block(IterRpgModBlocks.SPIRE_SPAWNER);
	public static final RegistryObject<Item> GRAND_SPIRE_SPAWNER = block(IterRpgModBlocks.GRAND_SPIRE_SPAWNER);
	public static final RegistryObject<Item> AMETRINE_HELMET = REGISTRY.register("ametrine_helmet", () -> new AmetrineItem.Helmet());
	public static final RegistryObject<Item> AMETRINE_CHESTPLATE = REGISTRY.register("ametrine_chestplate", () -> new AmetrineItem.Chestplate());
	public static final RegistryObject<Item> AMETRINE_LEGGINGS = REGISTRY.register("ametrine_leggings", () -> new AmetrineItem.Leggings());
	public static final RegistryObject<Item> AMETRINE_BOOTS = REGISTRY.register("ametrine_boots", () -> new AmetrineItem.Boots());
	public static final RegistryObject<Item> AMETRINE_SWORD = REGISTRY.register("ametrine_sword", () -> new AmetrineSwordItem());
	public static final RegistryObject<Item> AMETRINE_PICKAXE = REGISTRY.register("ametrine_pickaxe", () -> new AmetrinePickaxeItem());
	public static final RegistryObject<Item> AMETRINE_AXE = REGISTRY.register("ametrine_axe", () -> new AmetrineAxeItem());
	public static final RegistryObject<Item> AMETRINE_SHOVEL = REGISTRY.register("ametrine_shovel", () -> new AmetrineShovelItem());
	public static final RegistryObject<Item> AMETRINE_HOE = REGISTRY.register("ametrine_hoe", () -> new AmetrineHoeItem());
	public static final RegistryObject<Item> AMETRINE_DAGGER = REGISTRY.register("ametrine_dagger", () -> new AmetrineDaggerItem());
	public static final RegistryObject<Item> AMETRINE_SPEAR = REGISTRY.register("ametrine_spear", () -> new AmetrineSpearItem());
	public static final RegistryObject<Item> AMETRINE_SCYTHE = REGISTRY.register("ametrine_scythe", () -> new AmetrineScytheItem());
	public static final RegistryObject<Item> AMETRINE_FLAIL = REGISTRY.register("ametrine_flail", () -> new AmetrineFlailItem());
	public static final RegistryObject<Item> ESSENCE_OF_CREATION = REGISTRY.register("essence_of_creation", () -> new EssenceOfCreationItem());
	public static final RegistryObject<Item> SPELL_IGNITE = REGISTRY.register("spell_ignite", () -> new SpellIgniteItem());
	public static final RegistryObject<Item> SPELL_GUST = REGISTRY.register("spell_gust", () -> new SpellGustItem());
	public static final RegistryObject<Item> SPELL_SPLASHES = REGISTRY.register("spell_splashes", () -> new SpellSplashesItem());
	public static final RegistryObject<Item> BOTTLE_OF_OBSIDIAN_TEARS = REGISTRY.register("bottle_of_obsidian_tears", () -> new BottleOfObsidianTearsItem());
	public static final RegistryObject<Item> BONB = REGISTRY.register("bonb", () -> new BonbItem());
	public static final RegistryObject<Item> GOBSTEEL_JAVELIN = REGISTRY.register("gobsteel_javelin", () -> new GobsteelJavelinItem());
	public static final RegistryObject<Item> SPELL_CULTIVATE = REGISTRY.register("spell_cultivate", () -> new SpellCultivateItem());
	public static final RegistryObject<Item> SPELL_ATTRACT = REGISTRY.register("spell_attract", () -> new SpellAttractItem());
	public static final RegistryObject<Item> GRIMACE_TRAP = block(IterRpgModBlocks.GRIMACE_TRAP);
	public static final RegistryObject<Item> TEAR_CATCHER = block(IterRpgModBlocks.TEAR_CATCHER);
	public static final RegistryObject<Item> ETHERBLOOM_DECOCTION = REGISTRY.register("etherbloom_decoction", () -> new EtherbloomDecoctionItem());
	public static final RegistryObject<Item> GRIM_LOCKER = block(IterRpgModBlocks.GRIM_LOCKER);
	public static final RegistryObject<Item> SMALL_SCALLOP_SPAWN_EGG = REGISTRY.register("small_scallop_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.SMALL_SCALLOP, -10134683, -2706222, new Item.Properties()));
	public static final RegistryObject<Item> STRIPPED_SACRED_LOG = block(IterRpgModBlocks.STRIPPED_SACRED_LOG);
	public static final RegistryObject<Item> DEEPSTEEL_INGOT = REGISTRY.register("deepsteel_ingot", () -> new DeepsteelIngotItem());
	public static final RegistryObject<Item> DEEPSTEEL_SWORD = REGISTRY.register("deepsteel_sword", () -> new DeepsteelSwordItem());
	public static final RegistryObject<Item> DEEPSTEEL_PICKAXE = REGISTRY.register("deepsteel_pickaxe", () -> new DeepsteelPickaxeItem());
	public static final RegistryObject<Item> VOID_MAW = block(IterRpgModBlocks.VOID_MAW);
	public static final RegistryObject<Item> UNIDENTIFIED_SPELL = REGISTRY.register("unidentified_spell", () -> new UnidentifiedSpellItem());
	public static final RegistryObject<Item> WARPED_GOO = REGISTRY.register("warped_goo", () -> new WarpedGooItem());
	public static final RegistryObject<Item> ARCANIST_TABLE = block(IterRpgModBlocks.ARCANIST_TABLE);
	public static final RegistryObject<Item> SPELL_ETHERBOLT = REGISTRY.register("spell_etherbolt", () -> new SpellEtherboltItem());
	public static final RegistryObject<Item> SPELL_ETHERBLAST = REGISTRY.register("spell_etherblast", () -> new SpellEtherblastItem());
	public static final RegistryObject<Item> ABSTRUSE_CLOTH = REGISTRY.register("abstruse_cloth", () -> new AbstruseClothItem());
	public static final RegistryObject<Item> GIST = REGISTRY.register("gist", () -> new GistItem());
	public static final RegistryObject<Item> HALFLOWER = block(IterRpgModBlocks.HALFLOWER);
	public static final RegistryObject<Item> UNBOUND_SOUL_SPAWN_EGG = REGISTRY.register("unbound_soul_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.UNBOUND_SOUL, -7231558, -10127481, new Item.Properties()));
	public static final RegistryObject<Item> TOMBSTONE = block(IterRpgModBlocks.TOMBSTONE);
	public static final RegistryObject<Item> TOMBSTONE_FRAGMENT = REGISTRY.register("tombstone_fragment", () -> new TombstoneFragmentItem());
	public static final RegistryObject<Item> HAUNTED_SPLINTER = REGISTRY.register("haunted_splinter", () -> new HauntedSplinterItem());
	public static final RegistryObject<Item> ELEMENTAL_ARMOR_HELMET = REGISTRY.register("elemental_armor_helmet", () -> new ElementalArmorItem.Helmet());
	public static final RegistryObject<Item> ELEMENTAL_ARMOR_CHESTPLATE = REGISTRY.register("elemental_armor_chestplate", () -> new ElementalArmorItem.Chestplate());
	public static final RegistryObject<Item> ELEMENTAL_ARMOR_LEGGINGS = REGISTRY.register("elemental_armor_leggings", () -> new ElementalArmorItem.Leggings());
	public static final RegistryObject<Item> ELEMENTAL_ARMOR_BOOTS = REGISTRY.register("elemental_armor_boots", () -> new ElementalArmorItem.Boots());
	public static final RegistryObject<Item> GRAVE_CROSS = block(IterRpgModBlocks.GRAVE_CROSS);
	public static final RegistryObject<Item> ECTOPLASM = REGISTRY.register("ectoplasm", () -> new EctoplasmItem());
	public static final RegistryObject<Item> OTHERWORDLY_INGOT = REGISTRY.register("otherwordly_ingot", () -> new OtherwordlyIngotItem());
	public static final RegistryObject<Item> COIN_POUCH = REGISTRY.register("coin_pouch", () -> new CoinPouchItem());
	public static final RegistryObject<Item> SPELL_EMBERS = REGISTRY.register("spell_embers", () -> new SpellEmbersItem());
	public static final RegistryObject<Item> SPELL_DROPLETS = REGISTRY.register("spell_droplets", () -> new SpellDropletsItem());
	public static final RegistryObject<Item> SPELL_ZAP = REGISTRY.register("spell_zap", () -> new SpellZapItem());
	public static final RegistryObject<Item> GRIMSTONE_PEBBLE = REGISTRY.register("grimstone_pebble", () -> new GrimstonePebbleItem());
	public static final RegistryObject<Item> SPELL_POISON_GAS = REGISTRY.register("spell_poison_gas", () -> new SpellPoisonGasItem());
	public static final RegistryObject<Item> SPELL_SHADELASH = REGISTRY.register("spell_shadelash", () -> new SpellShadelashItem());
	public static final RegistryObject<Item> CHAOS_APPARITION_SPAWN_EGG = REGISTRY.register("chaos_apparition_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.CHAOS_APPARITION, -4973520, -10662293, new Item.Properties()));
	public static final RegistryObject<Item> SPELL_FLAMEBOLT = REGISTRY.register("spell_flamebolt", () -> new SpellFlameboltItem());
	public static final RegistryObject<Item> SMOOTH_MONOLITH_STONE = block(IterRpgModBlocks.SMOOTH_MONOLITH_STONE);
	public static final RegistryObject<Item> EARTH_RUNESTONE = block(IterRpgModBlocks.EARTH_RUNESTONE);
	public static final RegistryObject<Item> WATER_RUNESTONE = block(IterRpgModBlocks.WATER_RUNESTONE);
	public static final RegistryObject<Item> AIR_RUNESTONE = block(IterRpgModBlocks.AIR_RUNESTONE);
	public static final RegistryObject<Item> FIRE_RUNESTONE = block(IterRpgModBlocks.FIRE_RUNESTONE);
	public static final RegistryObject<Item> VOID_RUNESTONE = block(IterRpgModBlocks.VOID_RUNESTONE);
	public static final RegistryObject<Item> MONOLITH_DOOR = block(IterRpgModBlocks.MONOLITH_DOOR);
	public static final RegistryObject<Item> RUNE_OF_CHAOS = REGISTRY.register("rune_of_chaos", () -> new RuneOfChaosItem());
	public static final RegistryObject<Item> AMETHYST_WAND = REGISTRY.register("amethyst_wand", () -> new AmethystWandItem());
	public static final RegistryObject<Item> PEARL_WAND = REGISTRY.register("pearl_wand", () -> new PearlWandItem());
	public static final RegistryObject<Item> BONE_WAND = REGISTRY.register("bone_wand", () -> new BoneWandItem());
	public static final RegistryObject<Item> AMETRINE_STAFF = REGISTRY.register("ametrine_staff", () -> new AmetrineStaffItem());
	public static final RegistryObject<Item> NIMBLE_COPPER_SHORTSTAFF = REGISTRY.register("nimble_copper_shortstaff", () -> new NimbleCopperShortstaffItem());
	public static final RegistryObject<Item> DEEPSTEEL_AXE = REGISTRY.register("deepsteel_axe", () -> new DeepsteelAxeItem());
	public static final RegistryObject<Item> SWORD_OF_BOUNDING = REGISTRY.register("sword_of_bounding", () -> new SwordOfBoundingItem());
	public static final RegistryObject<Item> BLOOD_BOTTLE = REGISTRY.register("blood_bottle", () -> new BloodBottleItem());
	public static final RegistryObject<Item> TOMBSTONE_FRAGMENTS_BLOCK = block(IterRpgModBlocks.TOMBSTONE_FRAGMENTS_BLOCK);
	public static final RegistryObject<Item> TWIFFLE_BULB = block(IterRpgModBlocks.TWIFFLE_BULB);
	public static final RegistryObject<Item> SEVEN_SEAS_CONCOCTION = REGISTRY.register("seven_seas_concoction", () -> new SevenSeasConcoctionItem());
	public static final RegistryObject<Item> OBSCURITE = block(IterRpgModBlocks.OBSCURITE);
	public static final RegistryObject<Item> COBBLED_OBSCURITE = block(IterRpgModBlocks.COBBLED_OBSCURITE);
	public static final RegistryObject<Item> STARDUST_ICE = REGISTRY.register("stardust_ice", () -> new StardustIceItem());
	public static final RegistryObject<Item> HYDRA_STAFF = REGISTRY.register("hydra_staff", () -> new HydraStaffItem());
	public static final RegistryObject<Item> ABYSSQUARTZ_WAND = REGISTRY.register("abyssquartz_wand", () -> new AbyssquartzWandItem());
	public static final RegistryObject<Item> MAGMANUM_STAFF = REGISTRY.register("magmanum_staff", () -> new MagmanumStaffItem());
	public static final RegistryObject<Item> ENCHANTOME = REGISTRY.register("enchantome", () -> new EnchantomeItem());
	public static final RegistryObject<Item> ARCANE_BOUQUETE = REGISTRY.register("arcane_bouquete", () -> new ArcaneBouqueteItem());
	public static final RegistryObject<Item> VOLATILE_FIREBALL_LAUNCHER = REGISTRY.register("volatile_fireball_launcher", () -> new VolatileFireballLauncherItem());
	public static final RegistryObject<Item> SMOLDERING_TOME = REGISTRY.register("smoldering_tome", () -> new SmolderingTomeItem());
	public static final RegistryObject<Item> SPELL_VOIDBEAM = REGISTRY.register("spell_voidbeam", () -> new SpellVoidbeamItem());
	public static final RegistryObject<Item> THUNDERCLAP = REGISTRY.register("thunderclap", () -> new ThunderclapItem());
	public static final RegistryObject<Item> INK_BOTTLE = REGISTRY.register("ink_bottle", () -> new InkBottleItem());
	public static final RegistryObject<Item> ENCHANTED_PAGE = REGISTRY.register("enchanted_page", () -> new EnchantedPageItem());
	public static final RegistryObject<Item> SPELL_FROST_SPIKE = REGISTRY.register("spell_frost_spike", () -> new SpellFrostSpikeItem());
	public static final RegistryObject<Item> SPELL_SCRIBBLES = REGISTRY.register("spell_scribbles", () -> new SpellScribblesItem());
	public static final RegistryObject<Item> ANCIENT_KNOWLEDGE = REGISTRY.register("ancient_knowledge", () -> new AncientKnowledgeItem());
	public static final RegistryObject<Item> BLOODLETTER = REGISTRY.register("bloodletter", () -> new BloodletterItem());
	public static final RegistryObject<Item> SANGUARNET = REGISTRY.register("sanguarnet", () -> new SanguarnetItem());
	public static final RegistryObject<Item> AWAKENED_SANGUARNET = REGISTRY.register("awakened_sanguarnet", () -> new AwakenedSanguarnetItem());
	public static final RegistryObject<Item> SANGUARNET_ORE = block(IterRpgModBlocks.SANGUARNET_ORE);
	public static final RegistryObject<Item> FLESH_BLOCK = block(IterRpgModBlocks.FLESH_BLOCK);
	public static final RegistryObject<Item> THEWS_BLOCK = block(IterRpgModBlocks.THEWS_BLOCK);
	public static final RegistryObject<Item> TENDONS_BLOCK = block(IterRpgModBlocks.TENDONS_BLOCK);
	public static final RegistryObject<Item> BLOODROOT = block(IterRpgModBlocks.BLOODROOT);
	public static final RegistryObject<Item> NEURAL_APPENDAGE = block(IterRpgModBlocks.NEURAL_APPENDAGE);
	public static final RegistryObject<Item> TALL_NEURAL_APPENDAGE = doubleBlock(IterRpgModBlocks.TALL_NEURAL_APPENDAGE);
	public static final RegistryObject<Item> GLOWCYST = block(IterRpgModBlocks.GLOWCYST);
	public static final RegistryObject<Item> TALL_GLOWCYST = doubleBlock(IterRpgModBlocks.TALL_GLOWCYST);
	public static final RegistryObject<Item> NEURAL_FERN = doubleBlock(IterRpgModBlocks.NEURAL_FERN);
	public static final RegistryObject<Item> DEVILTHORN = block(IterRpgModBlocks.DEVILTHORN);
	public static final RegistryObject<Item> FLESH_WEAVER = REGISTRY.register(IterRpgModBlocks.FLESH_WEAVER.getId().getPath(), () -> new FleshWeaverDisplayItem(IterRpgModBlocks.FLESH_WEAVER.get(), new Item.Properties()));
	public static final RegistryObject<Item> SCAB_SPAWN_EGG = REGISTRY.register("scab_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.SCAB, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> DWARVEN_COMPONENTS = REGISTRY.register("dwarven_components", () -> new DwarvenComponentsItem());
	public static final RegistryObject<Item> COG_HEART = REGISTRY.register("cog_heart", () -> new CogHeartItem());
	public static final RegistryObject<Item> COMPONENT_DEPOSIT = block(IterRpgModBlocks.COMPONENT_DEPOSIT);
	public static final RegistryObject<Item> FLESHMITE_SPAWN_EGG = REGISTRY.register("fleshmite_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.FLESHMITE, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> REVENANT_SPAWN_EGG = REGISTRY.register("revenant_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.REVENANT, -3490672, -4973520, new Item.Properties()));
	public static final RegistryObject<Item> DEMONBONES = block(IterRpgModBlocks.DEMONBONES);
	public static final RegistryObject<Item> VILE_TISSUE = REGISTRY.register("vile_tissue", () -> new VileTissueItem());
	public static final RegistryObject<Item> DEMONBONE_FRAGMENTS = REGISTRY.register("demonbone_fragments", () -> new DemonboneFragmentsItem());
	public static final RegistryObject<Item> PROFANE_FLESH = REGISTRY.register("profane_flesh", () -> new ProfaneFleshItem());
	public static final RegistryObject<Item> DEMONBONE = REGISTRY.register("demonbone", () -> new DemonboneItem());
	public static final RegistryObject<Item> FIEND_SPAWN_EGG = REGISTRY.register("fiend_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.FIEND, -4379085, -3490672, new Item.Properties()));
	public static final RegistryObject<Item> DEMON_FANGS = block(IterRpgModBlocks.DEMON_FANGS);
	public static final RegistryObject<Item> IRON_RING = REGISTRY.register("iron_ring", () -> new IronRingItem());
	public static final RegistryObject<Item> GOLD_RING = REGISTRY.register("gold_ring", () -> new GoldRingItem());
	public static final RegistryObject<Item> NETHERITE_RING = REGISTRY.register("netherite_ring", () -> new NetheriteRingItem());
	public static final RegistryObject<Item> RING_MOULD = REGISTRY.register("ring_mould", () -> new RingMouldItem());
	public static final RegistryObject<Item> IRON_RING_AMETHYST = REGISTRY.register("iron_ring_amethyst", () -> new IronRingAmethystItem());
	public static final RegistryObject<Item> GOLD_RING_AMETHYST = REGISTRY.register("gold_ring_amethyst", () -> new GoldRingAmethystItem());
	public static final RegistryObject<Item> NETHERITE_RING_AMETHYST = REGISTRY.register("netherite_ring_amethyst", () -> new NetheriteRingAmethystItem());
	public static final RegistryObject<Item> IRON_RING_DIAMOND = REGISTRY.register("iron_ring_diamond", () -> new IronRingDiamondItem());
	public static final RegistryObject<Item> GOLD_RING_DIAMOND = REGISTRY.register("gold_ring_diamond", () -> new GoldRingDiamondItem());
	public static final RegistryObject<Item> NETHERITE_RING_DIAMOND = REGISTRY.register("netherite_ring_diamond", () -> new NetheriteRingDiamondItem());
	public static final RegistryObject<Item> IRON_RING_ABYSSQUARTZ = REGISTRY.register("iron_ring_abyssquartz", () -> new IronRingAbyssquartzItem());
	public static final RegistryObject<Item> GOLD_RING_ABYSSQUARTZ = REGISTRY.register("gold_ring_abyssquartz", () -> new GoldRingAbyssquartzItem());
	public static final RegistryObject<Item> NETHERITE_RING_ABYSSQUARTZ = REGISTRY.register("netherite_ring_abyssquartz", () -> new NetheriteRingAbyssquartzItem());
	public static final RegistryObject<Item> IRON_RING_MAGMANUM = REGISTRY.register("iron_ring_magmanum", () -> new IronRingMagmanumItem());
	public static final RegistryObject<Item> GOLD_RING_MAGMANUM = REGISTRY.register("gold_ring_magmanum", () -> new GoldRingMagmanumItem());
	public static final RegistryObject<Item> NETHERITE_RING_MAGMANUM = REGISTRY.register("netherite_ring_magmanum", () -> new NetheriteRingMagmanumItem());
	public static final RegistryObject<Item> IRON_RING_EMERALD = REGISTRY.register("iron_ring_emerald", () -> new IronRingEmeraldItem());
	public static final RegistryObject<Item> GOLD_RING_EMERALD = REGISTRY.register("gold_ring_emerald", () -> new GoldRingEmeraldItem());
	public static final RegistryObject<Item> NETHERITE_RING_EMERALD = REGISTRY.register("netherite_ring_emerald", () -> new NetheriteRingEmeraldItem());
	public static final RegistryObject<Item> FLAWLESS_DIAMOND = REGISTRY.register("flawless_diamond", () -> new FlawlessDiamondItem());
	public static final RegistryObject<Item> FLAWLESS_EMERALD = REGISTRY.register("flawless_emerald", () -> new FlawlessEmeraldItem());
	public static final RegistryObject<Item> FLAWLESS_MAGMANUM = REGISTRY.register("flawless_magmanum", () -> new FlawlessMagmanumItem());
	public static final RegistryObject<Item> IRON_RING_SANGUARNET = REGISTRY.register("iron_ring_sanguarnet", () -> new IronRingSanguarnetItem());
	public static final RegistryObject<Item> GOLD_RING_SANGUARNET = REGISTRY.register("gold_ring_sanguarnet", () -> new GoldRingSanguarnetItem());
	public static final RegistryObject<Item> NETHERITE_RING_SANGUARNET = REGISTRY.register("netherite_ring_sanguarnet", () -> new NetheriteRingSanguarnetItem());
	public static final RegistryObject<Item> PRIMORDIAL_FRAGMENT = REGISTRY.register("primordial_fragment", () -> new PrimordialFragmentItem());
	public static final RegistryObject<Item> PRIMORDIAL_INGOT = REGISTRY.register("primordial_ingot", () -> new PrimordialIngotItem());
	public static final RegistryObject<Item> EARTH_SWORD = REGISTRY.register("earth_sword", () -> new EarthSwordItem());
	public static final RegistryObject<Item> EARTH_SCYTHE = REGISTRY.register("earth_scythe", () -> new EarthScytheItem());
	public static final RegistryObject<Item> EARTH_SPEAR = REGISTRY.register("earth_spear", () -> new EarthSpearItem());
	public static final RegistryObject<Item> EARTH_FLAIL = REGISTRY.register("earth_flail", () -> new EarthFlailItem());
	public static final RegistryObject<Item> EARTH_DAGGER = REGISTRY.register("earth_dagger", () -> new EarthDaggerItem());
	public static final RegistryObject<Item> WATER_SWORD = REGISTRY.register("water_sword", () -> new WaterSwordItem());
	public static final RegistryObject<Item> WATER_SCYTHE = REGISTRY.register("water_scythe", () -> new WaterScytheItem());
	public static final RegistryObject<Item> WATER_SPEAR = REGISTRY.register("water_spear", () -> new WaterSpearItem());
	public static final RegistryObject<Item> WATER_FLAIL = REGISTRY.register("water_flail", () -> new WaterFlailItem());
	public static final RegistryObject<Item> WATER_DAGGER = REGISTRY.register("water_dagger", () -> new WaterDaggerItem());
	public static final RegistryObject<Item> AIR_SWORD = REGISTRY.register("air_sword", () -> new AirSwordItem());
	public static final RegistryObject<Item> AIR_SCYTHE = REGISTRY.register("air_scythe", () -> new AirScytheItem());
	public static final RegistryObject<Item> AIR_SPEAR = REGISTRY.register("air_spear", () -> new AirSpearItem());
	public static final RegistryObject<Item> AIR_FLAIL = REGISTRY.register("air_flail", () -> new AirFlailItem());
	public static final RegistryObject<Item> AIR_DAGGER = REGISTRY.register("air_dagger", () -> new AirDaggerItem());
	public static final RegistryObject<Item> FIRE_SWORD = REGISTRY.register("fire_sword", () -> new FireSwordItem());
	public static final RegistryObject<Item> FIRE_SCYTHE = REGISTRY.register("fire_scythe", () -> new FireScytheItem());
	public static final RegistryObject<Item> FIRE_SPEAR = REGISTRY.register("fire_spear", () -> new FireSpearItem());
	public static final RegistryObject<Item> FIRE_FLAIL = REGISTRY.register("fire_flail", () -> new FireFlailItem());
	public static final RegistryObject<Item> FIRE_DAGGER = REGISTRY.register("fire_dagger", () -> new FireDaggerItem());
	public static final RegistryObject<Item> VOID_SWORD = REGISTRY.register("void_sword", () -> new VoidSwordItem());
	public static final RegistryObject<Item> VOID_SCYTHE = REGISTRY.register("void_scythe", () -> new VoidScytheItem());
	public static final RegistryObject<Item> VOID_SPEAR = REGISTRY.register("void_spear", () -> new VoidSpearItem());
	public static final RegistryObject<Item> VOID_FLAIL = REGISTRY.register("void_flail", () -> new VoidFlailItem());
	public static final RegistryObject<Item> VOID_DAGGER = REGISTRY.register("void_dagger", () -> new VoidDaggerItem());
	public static final RegistryObject<Item> EARTH_ARMOR_HELMET = REGISTRY.register("earth_armor_helmet", () -> new EarthArmorItem.Helmet());
	public static final RegistryObject<Item> EARTH_ARMOR_CHESTPLATE = REGISTRY.register("earth_armor_chestplate", () -> new EarthArmorItem.Chestplate());
	public static final RegistryObject<Item> EARTH_ARMOR_LEGGINGS = REGISTRY.register("earth_armor_leggings", () -> new EarthArmorItem.Leggings());
	public static final RegistryObject<Item> EARTH_ARMOR_BOOTS = REGISTRY.register("earth_armor_boots", () -> new EarthArmorItem.Boots());
	public static final RegistryObject<Item> WATER_ARMOR_HELMET = REGISTRY.register("water_armor_helmet", () -> new WaterArmorItem.Helmet());
	public static final RegistryObject<Item> WATER_ARMOR_CHESTPLATE = REGISTRY.register("water_armor_chestplate", () -> new WaterArmorItem.Chestplate());
	public static final RegistryObject<Item> WATER_ARMOR_LEGGINGS = REGISTRY.register("water_armor_leggings", () -> new WaterArmorItem.Leggings());
	public static final RegistryObject<Item> WATER_ARMOR_BOOTS = REGISTRY.register("water_armor_boots", () -> new WaterArmorItem.Boots());
	public static final RegistryObject<Item> AIR_ARMOR_HELMET = REGISTRY.register("air_armor_helmet", () -> new AirArmorItem.Helmet());
	public static final RegistryObject<Item> AIR_ARMOR_CHESTPLATE = REGISTRY.register("air_armor_chestplate", () -> new AirArmorItem.Chestplate());
	public static final RegistryObject<Item> AIR_ARMOR_LEGGINGS = REGISTRY.register("air_armor_leggings", () -> new AirArmorItem.Leggings());
	public static final RegistryObject<Item> AIR_ARMOR_BOOTS = REGISTRY.register("air_armor_boots", () -> new AirArmorItem.Boots());
	public static final RegistryObject<Item> FIRE_ARMOR_HELMET = REGISTRY.register("fire_armor_helmet", () -> new FireArmorItem.Helmet());
	public static final RegistryObject<Item> FIRE_ARMOR_CHESTPLATE = REGISTRY.register("fire_armor_chestplate", () -> new FireArmorItem.Chestplate());
	public static final RegistryObject<Item> FIRE_ARMOR_LEGGINGS = REGISTRY.register("fire_armor_leggings", () -> new FireArmorItem.Leggings());
	public static final RegistryObject<Item> FIRE_ARMOR_BOOTS = REGISTRY.register("fire_armor_boots", () -> new FireArmorItem.Boots());
	public static final RegistryObject<Item> FIRESTARTER = REGISTRY.register("firestarter", () -> new FirestarterItem());
	public static final RegistryObject<Item> VOID_ARMOR_HELMET = REGISTRY.register("void_armor_helmet", () -> new VoidArmorItem.Helmet());
	public static final RegistryObject<Item> VOID_ARMOR_CHESTPLATE = REGISTRY.register("void_armor_chestplate", () -> new VoidArmorItem.Chestplate());
	public static final RegistryObject<Item> VOID_ARMOR_LEGGINGS = REGISTRY.register("void_armor_leggings", () -> new VoidArmorItem.Leggings());
	public static final RegistryObject<Item> VOID_ARMOR_BOOTS = REGISTRY.register("void_armor_boots", () -> new VoidArmorItem.Boots());
	public static final RegistryObject<Item> FESTERING_WINGS = REGISTRY.register("festering_wings", () -> new FesteringWingsItem());
	public static final RegistryObject<Item> CRUNCHER = block(IterRpgModBlocks.CRUNCHER);
	public static final RegistryObject<Item> SANGUARNET_BLOCK = block(IterRpgModBlocks.SANGUARNET_BLOCK);
	public static final RegistryObject<Item> EARTH_PICKAXE = REGISTRY.register("earth_pickaxe", () -> new EarthPickaxeItem());
	public static final RegistryObject<Item> WATER_PICKAXE = REGISTRY.register("water_pickaxe", () -> new WaterPickaxeItem());
	public static final RegistryObject<Item> AIR_PICKAXE = REGISTRY.register("air_pickaxe", () -> new AirPickaxeItem());
	public static final RegistryObject<Item> FIRE_PICKAXE = REGISTRY.register("fire_pickaxe", () -> new FirePickaxeItem());
	public static final RegistryObject<Item> VOID_PICKAXE = REGISTRY.register("void_pickaxe", () -> new VoidPickaxeItem());
	public static final RegistryObject<Item> EARTH_AXE = REGISTRY.register("earth_axe", () -> new EarthAxeItem());
	public static final RegistryObject<Item> WATER_AXE = REGISTRY.register("water_axe", () -> new WaterAxeItem());
	public static final RegistryObject<Item> AIR_AXE = REGISTRY.register("air_axe", () -> new AirAxeItem());
	public static final RegistryObject<Item> FIRE_AXE = REGISTRY.register("fire_axe", () -> new FireAxeItem());
	public static final RegistryObject<Item> VOID_AXE = REGISTRY.register("void_axe", () -> new VoidAxeItem());
	public static final RegistryObject<Item> EARTH_SHOVEL = REGISTRY.register("earth_shovel", () -> new EarthShovelItem());
	public static final RegistryObject<Item> WATER_SHOVEL = REGISTRY.register("water_shovel", () -> new WaterShovelItem());
	public static final RegistryObject<Item> AIR_SHOVEL = REGISTRY.register("air_shovel", () -> new AirShovelItem());
	public static final RegistryObject<Item> FIRE_SHOVEL = REGISTRY.register("fire_shovel", () -> new FireShovelItem());
	public static final RegistryObject<Item> VOID_SHOVEL = REGISTRY.register("void_shovel", () -> new VoidShovelItem());
	public static final RegistryObject<Item> EARTH_HOE = REGISTRY.register("earth_hoe", () -> new EarthHoeItem());
	public static final RegistryObject<Item> WATER_HOE = REGISTRY.register("water_hoe", () -> new WaterHoeItem());
	public static final RegistryObject<Item> AIR_HOE = REGISTRY.register("air_hoe", () -> new AirHoeItem());
	public static final RegistryObject<Item> FIRE_HOE = REGISTRY.register("fire_hoe", () -> new FireHoeItem());
	public static final RegistryObject<Item> VOID_HOE = REGISTRY.register("void_hoe", () -> new VoidHoeItem());
	public static final RegistryObject<Item> SPELL_RECALL = REGISTRY.register("spell_recall", () -> new SpellRecallItem());
	public static final RegistryObject<Item> SPELL_MEND = REGISTRY.register("spell_mend", () -> new SpellMendItem());
	public static final RegistryObject<Item> PEBBLE_LAUNCHER = block(IterRpgModBlocks.PEBBLE_LAUNCHER);
	public static final RegistryObject<Item> AZURE_HELMET = REGISTRY.register("azure_helmet", () -> new AzureItem.Helmet());
	public static final RegistryObject<Item> AZURE_CHESTPLATE = REGISTRY.register("azure_chestplate", () -> new AzureItem.Chestplate());
	public static final RegistryObject<Item> AZURE_LEGGINGS = REGISTRY.register("azure_leggings", () -> new AzureItem.Leggings());
	public static final RegistryObject<Item> AZURE_BOOTS = REGISTRY.register("azure_boots", () -> new AzureItem.Boots());
	public static final RegistryObject<Item> ETHERBREW = REGISTRY.register("etherbrew", () -> new EtherbrewItem());
	public static final RegistryObject<Item> GNAWER = block(IterRpgModBlocks.GNAWER);
	public static final RegistryObject<Item> BOWSTRING = REGISTRY.register("bowstring", () -> new BowstringItem());
	public static final RegistryObject<Item> RECURVE_BOW = REGISTRY.register("recurve_bow", () -> new RecurveBowItem());
	public static final RegistryObject<Item> THE_ROCK = REGISTRY.register("the_rock", () -> new TheRockItem());
	public static final RegistryObject<Item> DAMNED_HELMET = REGISTRY.register("damned_helmet", () -> new DamnedItem.Helmet());
	public static final RegistryObject<Item> DAMNED_CHESTPLATE = REGISTRY.register("damned_chestplate", () -> new DamnedItem.Chestplate());
	public static final RegistryObject<Item> DAMNED_LEGGINGS = REGISTRY.register("damned_leggings", () -> new DamnedItem.Leggings());
	public static final RegistryObject<Item> DAMNED_BOOTS = REGISTRY.register("damned_boots", () -> new DamnedItem.Boots());
	public static final RegistryObject<Item> AXEBEAK_SPAWN_EGG = REGISTRY.register("axebeak_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.AXEBEAK, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> AXEBEAK_FEATHER = REGISTRY.register("axebeak_feather", () -> new AxebeakFeatherItem());
	public static final RegistryObject<Item> AXEBEAK_MEAT = REGISTRY.register("axebeak_meat", () -> new AxebeakMeatItem());

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}

	private static RegistryObject<Item> doubleBlock(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new DoubleHighBlockItem(block.get(), new Item.Properties()));
	}

	@SubscribeEvent
	public static void clientLoad(FMLClientSetupEvent event) {
		event.enqueueWork(() -> {
			ItemProperties.register(BLOODBRANCH.get(), new ResourceLocation("iter_rpg:bloodbranch_pulling"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) BloodbranchProvideValueProcedure.execute(entity, itemStackToRender));
			ItemProperties.register(STINGER.get(), new ResourceLocation("iter_rpg:stinger_pulling"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) GetPullingValueProcedure.execute(entity, itemStackToRender));
			ItemProperties.register(DRIFTBOW.get(), new ResourceLocation("iter_rpg:driftbow_pulling"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) GetPullingValueProcedure.execute(entity, itemStackToRender));
			ItemProperties.register(FIRESTARTER.get(), new ResourceLocation("iter_rpg:firestarter_pulling"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) GetPullingValueProcedure.execute(entity, itemStackToRender));
			ItemProperties.register(RECURVE_BOW.get(), new ResourceLocation("iter_rpg:recurve_bow_pulling"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) GetPullingValueProcedure.execute(entity, itemStackToRender));
		});
	}
}
