
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.thirdlife.iterrpg.init;

import net.thirdlife.iterrpg.procedures.BloodbranchProvideValueProcedure;
import net.thirdlife.iterrpg.item.WoodenSpearItem;
import net.thirdlife.iterrpg.item.WoodenScytheItem;
import net.thirdlife.iterrpg.item.WoodenFlailItem;
import net.thirdlife.iterrpg.item.WoddenDaggerItem;
import net.thirdlife.iterrpg.item.WaterRuneItem;
import net.thirdlife.iterrpg.item.WaterIngotItem;
import net.thirdlife.iterrpg.item.WaterFragmentItem;
import net.thirdlife.iterrpg.item.WarpedGooItem;
import net.thirdlife.iterrpg.item.VoidRuneItem;
import net.thirdlife.iterrpg.item.VoidIngotItem;
import net.thirdlife.iterrpg.item.VoidFragmentItem;
import net.thirdlife.iterrpg.item.VileTissueItem;
import net.thirdlife.iterrpg.item.VeryGoodAndCheerfulRapierItem;
import net.thirdlife.iterrpg.item.UnidentifiedSpellItem;
import net.thirdlife.iterrpg.item.TwiffleLumpItem;
import net.thirdlife.iterrpg.item.TormentorItem;
import net.thirdlife.iterrpg.item.TombstoneFragmentItem;
import net.thirdlife.iterrpg.item.StormcallerItem;
import net.thirdlife.iterrpg.item.StoneSpearItem;
import net.thirdlife.iterrpg.item.StoneScytheItem;
import net.thirdlife.iterrpg.item.StoneGeodeItem;
import net.thirdlife.iterrpg.item.StoneFlailItem;
import net.thirdlife.iterrpg.item.StoneDaggerItem;
import net.thirdlife.iterrpg.item.StingerItem;
import net.thirdlife.iterrpg.item.StarlessnessItem;
import net.thirdlife.iterrpg.item.StarfishItem;
import net.thirdlife.iterrpg.item.SpiderSilkItem;
import net.thirdlife.iterrpg.item.SpiderMeadMugItem;
import net.thirdlife.iterrpg.item.SpellZapItem;
import net.thirdlife.iterrpg.item.SpellSplashesItem;
import net.thirdlife.iterrpg.item.SpellIgniteItem;
import net.thirdlife.iterrpg.item.SpellHealItem;
import net.thirdlife.iterrpg.item.SpellGustItem;
import net.thirdlife.iterrpg.item.SpellEtherboltItem;
import net.thirdlife.iterrpg.item.SpellEtherblastItem;
import net.thirdlife.iterrpg.item.SpellEmbersItem;
import net.thirdlife.iterrpg.item.SpellDropletsItem;
import net.thirdlife.iterrpg.item.SpellCultivateItem;
import net.thirdlife.iterrpg.item.SpellBookItem;
import net.thirdlife.iterrpg.item.SpellAttractItem;
import net.thirdlife.iterrpg.item.SpawnerFragmentItem;
import net.thirdlife.iterrpg.item.SolsticeItem;
import net.thirdlife.iterrpg.item.SeashellItem;
import net.thirdlife.iterrpg.item.SacrificialDaggerItem;
import net.thirdlife.iterrpg.item.SacredTwigItem;
import net.thirdlife.iterrpg.item.RaggedItem;
import net.thirdlife.iterrpg.item.ProfaneFleshItem;
import net.thirdlife.iterrpg.item.PotsherdItem;
import net.thirdlife.iterrpg.item.PearlItem;
import net.thirdlife.iterrpg.item.OtherwordlyIngotItem;
import net.thirdlife.iterrpg.item.NetherrackGeodeItem;
import net.thirdlife.iterrpg.item.NetheriteSpearItem;
import net.thirdlife.iterrpg.item.NetheriteScytheItem;
import net.thirdlife.iterrpg.item.NetheriteFlailItem;
import net.thirdlife.iterrpg.item.NetheriteDaggerItem;
import net.thirdlife.iterrpg.item.MugItem;
import net.thirdlife.iterrpg.item.MobPlacerItem;
import net.thirdlife.iterrpg.item.MarrowItem;
import net.thirdlife.iterrpg.item.MagmanumSwordItem;
import net.thirdlife.iterrpg.item.MagmanumPickaxeItem;
import net.thirdlife.iterrpg.item.MagmanumChunkItem;
import net.thirdlife.iterrpg.item.MagmanumArmorItem;
import net.thirdlife.iterrpg.item.IronSpearItem;
import net.thirdlife.iterrpg.item.IronScytheItem;
import net.thirdlife.iterrpg.item.IronFlailItem;
import net.thirdlife.iterrpg.item.IronDaggerItem;
import net.thirdlife.iterrpg.item.HumieButcherItem;
import net.thirdlife.iterrpg.item.HollowVisageItem;
import net.thirdlife.iterrpg.item.HauntedSplinterItem;
import net.thirdlife.iterrpg.item.HarvestItem;
import net.thirdlife.iterrpg.item.GoldenSpearItem;
import net.thirdlife.iterrpg.item.GoldenScytheItem;
import net.thirdlife.iterrpg.item.GoldenFlailItem;
import net.thirdlife.iterrpg.item.GoldenDaggerItem;
import net.thirdlife.iterrpg.item.GobsteelScrapItem;
import net.thirdlife.iterrpg.item.GobsteelJavelinItem;
import net.thirdlife.iterrpg.item.GistItem;
import net.thirdlife.iterrpg.item.GiantWeeperTearItem;
import net.thirdlife.iterrpg.item.FireRuneItem;
import net.thirdlife.iterrpg.item.FireIngotItem;
import net.thirdlife.iterrpg.item.FireFragmentItem;
import net.thirdlife.iterrpg.item.EtherbloomDecoctionItem;
import net.thirdlife.iterrpg.item.EternalTorrentItem;
import net.thirdlife.iterrpg.item.EssenceOfCreationItem;
import net.thirdlife.iterrpg.item.EndstoneGeodeItem;
import net.thirdlife.iterrpg.item.EmptyRuneItem;
import net.thirdlife.iterrpg.item.ElementalUpgradeItem;
import net.thirdlife.iterrpg.item.ElementalSwordItem;
import net.thirdlife.iterrpg.item.ElementalIngotItem;
import net.thirdlife.iterrpg.item.ElementalFragmentItem;
import net.thirdlife.iterrpg.item.ElementalArmorItem;
import net.thirdlife.iterrpg.item.EctoplasmItem;
import net.thirdlife.iterrpg.item.EarthRuneItem;
import net.thirdlife.iterrpg.item.EarthIngotItem;
import net.thirdlife.iterrpg.item.EarthFragmentItem;
import net.thirdlife.iterrpg.item.DriftbowItem;
import net.thirdlife.iterrpg.item.DiamondSpearItem;
import net.thirdlife.iterrpg.item.DiamondScytheItem;
import net.thirdlife.iterrpg.item.DiamondFlailItem;
import net.thirdlife.iterrpg.item.DiamondDaggerItem;
import net.thirdlife.iterrpg.item.DemonboneItem;
import net.thirdlife.iterrpg.item.DemonboneFragmentsItem;
import net.thirdlife.iterrpg.item.DeepsteelSwordItem;
import net.thirdlife.iterrpg.item.DeepsteelPickaxeItem;
import net.thirdlife.iterrpg.item.DeepsteelIngotItem;
import net.thirdlife.iterrpg.item.DeepslateGeodeItem;
import net.thirdlife.iterrpg.item.CrystalTearItem;
import net.thirdlife.iterrpg.item.CrescentItem;
import net.thirdlife.iterrpg.item.CoinPouchItem;
import net.thirdlife.iterrpg.item.CoinItem;
import net.thirdlife.iterrpg.item.CaltropItem;
import net.thirdlife.iterrpg.item.CalibratedLensItem;
import net.thirdlife.iterrpg.item.BottleOfObsidianTearsItem;
import net.thirdlife.iterrpg.item.BonbItem;
import net.thirdlife.iterrpg.item.BloodthirstItem;
import net.thirdlife.iterrpg.item.BloodbranchItem;
import net.thirdlife.iterrpg.item.BlackstoneGeodeItem;
import net.thirdlife.iterrpg.item.BeerMugItem;
import net.thirdlife.iterrpg.item.ArcanePowderItem;
import net.thirdlife.iterrpg.item.AmetrineSwordItem;
import net.thirdlife.iterrpg.item.AmetrineSpearItem;
import net.thirdlife.iterrpg.item.AmetrineShovelItem;
import net.thirdlife.iterrpg.item.AmetrineScytheItem;
import net.thirdlife.iterrpg.item.AmetrinePickaxeItem;
import net.thirdlife.iterrpg.item.AmetrinePendantItem;
import net.thirdlife.iterrpg.item.AmetrineNuggetItem;
import net.thirdlife.iterrpg.item.AmetrineItem;
import net.thirdlife.iterrpg.item.AmetrineIngotItem;
import net.thirdlife.iterrpg.item.AmetrineHoeItem;
import net.thirdlife.iterrpg.item.AmetrineFlailItem;
import net.thirdlife.iterrpg.item.AmetrineDaggerItem;
import net.thirdlife.iterrpg.item.AmetrineAxeItem;
import net.thirdlife.iterrpg.item.AmethystWandItem;
import net.thirdlife.iterrpg.item.AirRuneItem;
import net.thirdlife.iterrpg.item.AirIngotItem;
import net.thirdlife.iterrpg.item.AirFragmentItem;
import net.thirdlife.iterrpg.item.AbyssquartzShardItem;
import net.thirdlife.iterrpg.item.AbyssquartzCapacitatorItem;
import net.thirdlife.iterrpg.item.AbstruseClothItem;
import net.thirdlife.iterrpg.IterRpgMod;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.common.ForgeSpawnEggItem;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.client.renderer.item.ItemProperties;

@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
public class IterRpgModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, IterRpgMod.MODID);
	public static final RegistryObject<Item> GRIMSTONE = block(IterRpgModBlocks.GRIMSTONE);
	public static final RegistryObject<Item> GRIMSTONE_BRICKS = block(IterRpgModBlocks.GRIMSTONE_BRICKS);
	public static final RegistryObject<Item> CRACKED_GRIMSTONE_BRICKS = block(IterRpgModBlocks.CRACKED_GRIMSTONE_BRICKS);
	public static final RegistryObject<Item> GRIMSTONE_BRICKS_SLAB = block(IterRpgModBlocks.GRIMSTONE_BRICKS_SLAB);
	public static final RegistryObject<Item> POLISHED_GRIMSTONE = block(IterRpgModBlocks.POLISHED_GRIMSTONE);
	public static final RegistryObject<Item> GRIMSTONE_SLAB = block(IterRpgModBlocks.GRIMSTONE_SLAB);
	public static final RegistryObject<Item> POLISHED_GRIMSTONE_SLAB = block(IterRpgModBlocks.POLISHED_GRIMSTONE_SLAB);
	public static final RegistryObject<Item> AMETRINE_INGOT = REGISTRY.register("ametrine_ingot", () -> new AmetrineIngotItem());
	public static final RegistryObject<Item> SPAWNER_FRAGMENT = REGISTRY.register("spawner_fragment", () -> new SpawnerFragmentItem());
	public static final RegistryObject<Item> COIN = REGISTRY.register("coin", () -> new CoinItem());
	public static final RegistryObject<Item> POLISHED_GRIMSTONE_STAIRS = block(IterRpgModBlocks.POLISHED_GRIMSTONE_STAIRS);
	public static final RegistryObject<Item> GRIMSTONE_BRICKS_STAIRS = block(IterRpgModBlocks.GRIMSTONE_BRICKS_STAIRS);
	public static final RegistryObject<Item> POLISHED_GRIMSTONE_WALL = block(IterRpgModBlocks.POLISHED_GRIMSTONE_WALL);
	public static final RegistryObject<Item> GRIMSTONE_BRICKS_WALL = block(IterRpgModBlocks.GRIMSTONE_BRICKS_WALL);
	public static final RegistryObject<Item> CHISELED_GRIMSTONE_BRICKS = block(IterRpgModBlocks.CHISELED_GRIMSTONE_BRICKS);
	public static final RegistryObject<Item> SMALL_VASE = block(IterRpgModBlocks.SMALL_VASE);
	public static final RegistryObject<Item> VASE = block(IterRpgModBlocks.VASE);
	public static final RegistryObject<Item> BIG_VASE = block(IterRpgModBlocks.BIG_VASE);
	public static final RegistryObject<Item> AMETRINE_BLOCK = block(IterRpgModBlocks.AMETRINE_BLOCK);
	public static final RegistryObject<Item> ETHERBLOOM = block(IterRpgModBlocks.ETHERBLOOM);
	public static final RegistryObject<Item> ARCANE_FLOWER_SEEDS = block(IterRpgModBlocks.ARCANE_FLOWER_SEEDS);
	public static final RegistryObject<Item> ETHER_DUST = REGISTRY.register("ether_dust", () -> new ArcanePowderItem());
	public static final RegistryObject<Item> WOODEN_FLAIL = REGISTRY.register("wooden_flail", () -> new WoodenFlailItem());
	public static final RegistryObject<Item> STONE_FLAIL = REGISTRY.register("stone_flail", () -> new StoneFlailItem());
	public static final RegistryObject<Item> IRON_FLAIL = REGISTRY.register("iron_flail", () -> new IronFlailItem());
	public static final RegistryObject<Item> GOLDEN_FLAIL = REGISTRY.register("golden_flail", () -> new GoldenFlailItem());
	public static final RegistryObject<Item> DIAMOND_FLAIL = REGISTRY.register("diamond_flail", () -> new DiamondFlailItem());
	public static final RegistryObject<Item> NETHERITE_FLAIL = REGISTRY.register("netherite_flail", () -> new NetheriteFlailItem());
	public static final RegistryObject<Item> WOODEN_SCYTHE = REGISTRY.register("wooden_scythe", () -> new WoodenScytheItem());
	public static final RegistryObject<Item> STONE_SCYTHE = REGISTRY.register("stone_scythe", () -> new StoneScytheItem());
	public static final RegistryObject<Item> IRON_SCYTHE = REGISTRY.register("iron_scythe", () -> new IronScytheItem());
	public static final RegistryObject<Item> GOLDEN_SCYTHE = REGISTRY.register("golden_scythe", () -> new GoldenScytheItem());
	public static final RegistryObject<Item> DIAMOND_SCYTHE = REGISTRY.register("diamond_scythe", () -> new DiamondScytheItem());
	public static final RegistryObject<Item> NETHERITE_SCYTHE = REGISTRY.register("netherite_scythe", () -> new NetheriteScytheItem());
	public static final RegistryObject<Item> GENERIC_DUNGEON_GEN_BLOCK = block(IterRpgModBlocks.GENERIC_DUNGEON_GEN_BLOCK);
	public static final RegistryObject<Item> GRIEVER_SPAWN_EGG = REGISTRY.register("griever_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.GRIEVER, -13686721, -15531998, new Item.Properties()));
	public static final RegistryObject<Item> MOURNSTONE_SPAWN_EGG = REGISTRY.register("mournstone_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.MOURNSTONE, -13686721, -1020441, new Item.Properties()));
	public static final RegistryObject<Item> MAGMANUM_CHUNK = REGISTRY.register("magmanum_chunk", () -> new MagmanumChunkItem());
	public static final RegistryObject<Item> MAGMANUM_ORE = block(IterRpgModBlocks.MAGMANUM_ORE);
	public static final RegistryObject<Item> GEODITE = block(IterRpgModBlocks.GEODITE);
	public static final RegistryObject<Item> BLACKSTONE_GEODITE = block(IterRpgModBlocks.BLACKSTONE_GEODITE);
	public static final RegistryObject<Item> EARTH_RUNE = REGISTRY.register("earth_rune", () -> new EarthRuneItem());
	public static final RegistryObject<Item> GOBLIN_WARRIOR_SPAWN_EGG = REGISTRY.register("goblin_warrior_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.GOBLIN_WARRIOR, -5392333, -7500906, new Item.Properties()));
	public static final RegistryObject<Item> WATER_RUNE = REGISTRY.register("water_rune", () -> new WaterRuneItem());
	public static final RegistryObject<Item> WATER_FRAGMENT = REGISTRY.register("water_fragment", () -> new WaterFragmentItem());
	public static final RegistryObject<Item> EMPTY_RUNE = REGISTRY.register("empty_rune", () -> new EmptyRuneItem());
	public static final RegistryObject<Item> FIRE_ELEMENTAL_SPAWN_EGG = REGISTRY.register("fire_elemental_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.FIRE_ELEMENTAL, -6213352, -1917878, new Item.Properties()));
	public static final RegistryObject<Item> EARTH_FRAGMENT = REGISTRY.register("earth_fragment", () -> new EarthFragmentItem());
	public static final RegistryObject<Item> BLOATED_SPAWN_EGG = REGISTRY.register("bloated_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.BLOATED, -11693440, -10100515, new Item.Properties()));
	public static final RegistryObject<Item> MAGMANUM_ARMOR_HELMET = REGISTRY.register("magmanum_armor_helmet", () -> new MagmanumArmorItem.Helmet());
	public static final RegistryObject<Item> MAGMANUM_ARMOR_CHESTPLATE = REGISTRY.register("magmanum_armor_chestplate", () -> new MagmanumArmorItem.Chestplate());
	public static final RegistryObject<Item> MAGMANUM_ARMOR_LEGGINGS = REGISTRY.register("magmanum_armor_leggings", () -> new MagmanumArmorItem.Leggings());
	public static final RegistryObject<Item> MAGMANUM_ARMOR_BOOTS = REGISTRY.register("magmanum_armor_boots", () -> new MagmanumArmorItem.Boots());
	public static final RegistryObject<Item> EARTH_ELEMENTAL_SPAWN_EGG = REGISTRY.register("earth_elemental_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.EARTH_ELEMENTAL, -10730928, -11030686, new Item.Properties()));
	public static final RegistryObject<Item> MAGMANUM_BLOCK = block(IterRpgModBlocks.MAGMANUM_BLOCK);
	public static final RegistryObject<Item> WEEPER_SPAWN_EGG = REGISTRY.register("weeper_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.WEEPER, -13686721, -14349255, new Item.Properties()));
	public static final RegistryObject<Item> CRYSTAL_TEAR = REGISTRY.register("crystal_tear", () -> new CrystalTearItem());
	public static final RegistryObject<Item> CHARGED_GRIMSTONE_BRICKS = block(IterRpgModBlocks.CHARGED_GRIMSTONE_BRICKS);
	public static final RegistryObject<Item> GRIM_KEYHOLE = block(IterRpgModBlocks.GRIM_KEYHOLE);
	public static final RegistryObject<Item> SORROWSEALED_SPAWN_EGG = REGISTRY.register("sorrowsealed_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.SORROWSEALED, -11580839, -1020441, new Item.Properties()));
	public static final RegistryObject<Item> SORROW_SPIRE_GEN_BLOCK = block(IterRpgModBlocks.SORROW_SPIRE_GEN_BLOCK);
	public static final RegistryObject<Item> WITCHMUD = block(IterRpgModBlocks.WITCHMUD);
	public static final RegistryObject<Item> CATTAIL = doubleBlock(IterRpgModBlocks.CATTAIL);
	public static final RegistryObject<Item> BLOODBRANCH = REGISTRY.register("bloodbranch", () -> new BloodbranchItem());
	public static final RegistryObject<Item> GIANT_CHAIN = block(IterRpgModBlocks.GIANT_CHAIN);
	public static final RegistryObject<Item> COMPACTED_SORROWSEALED = block(IterRpgModBlocks.COMPACTED_SORROWSEALED);
	public static final RegistryObject<Item> TORMENTOR = REGISTRY.register("tormentor", () -> new TormentorItem());
	public static final RegistryObject<Item> DEMONBONE = REGISTRY.register("demonbone", () -> new DemonboneItem());
	public static final RegistryObject<Item> SCALLOP_SPAWN_EGG = REGISTRY.register("scallop_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.SCALLOP, -10134683, -2706222, new Item.Properties()));
	public static final RegistryObject<Item> GIANT_SPIDER_SPAWN_EGG = REGISTRY.register("giant_spider_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.GIANT_SPIDER, -12766183, -5763570, new Item.Properties()));
	public static final RegistryObject<Item> SPIDER_EGG = block(IterRpgModBlocks.SPIDER_EGG);
	public static final RegistryObject<Item> SPIDER_SILK = REGISTRY.register("spider_silk", () -> new SpiderSilkItem());
	public static final RegistryObject<Item> SPIDERLING_SPAWN_EGG = REGISTRY.register("spiderling_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.SPIDERLING, -2372425, -13029294, new Item.Properties()));
	public static final RegistryObject<Item> HIVESTONE = block(IterRpgModBlocks.HIVESTONE);
	public static final RegistryObject<Item> TWIFFLE = block(IterRpgModBlocks.TWIFFLE);
	public static final RegistryObject<Item> TWIFFLE_BLOCK = block(IterRpgModBlocks.TWIFFLE_BLOCK);
	public static final RegistryObject<Item> TWIFFLE_LUMP = REGISTRY.register("twiffle_lump", () -> new TwiffleLumpItem());
	public static final RegistryObject<Item> AIR_RUNE = REGISTRY.register("air_rune", () -> new AirRuneItem());
	public static final RegistryObject<Item> FIRE_RUNE = REGISTRY.register("fire_rune", () -> new FireRuneItem());
	public static final RegistryObject<Item> VOID_RUNE = REGISTRY.register("void_rune", () -> new VoidRuneItem());
	public static final RegistryObject<Item> AIR_FRAGMENT = REGISTRY.register("air_fragment", () -> new AirFragmentItem());
	public static final RegistryObject<Item> FIRE_FRAGMENT = REGISTRY.register("fire_fragment", () -> new FireFragmentItem());
	public static final RegistryObject<Item> CUT_HIVESTONE = block(IterRpgModBlocks.CUT_HIVESTONE);
	public static final RegistryObject<Item> CRACKED_HIVESTONE = block(IterRpgModBlocks.CRACKED_HIVESTONE);
	public static final RegistryObject<Item> CRUMBLING_HIVESTONE = block(IterRpgModBlocks.CRUMBLING_HIVESTONE);
	public static final RegistryObject<Item> RUNIC_HIVESTONE = block(IterRpgModBlocks.RUNIC_HIVESTONE);
	public static final RegistryObject<Item> SILKY_HIVESTONE = block(IterRpgModBlocks.SILKY_HIVESTONE);
	public static final RegistryObject<Item> WEAVED_HIVESTONE = block(IterRpgModBlocks.WEAVED_HIVESTONE);
	public static final RegistryObject<Item> INFESTED_HIVESTONE = block(IterRpgModBlocks.INFESTED_HIVESTONE);
	public static final RegistryObject<Item> HIVESTONE_SLAB = block(IterRpgModBlocks.HIVESTONE_SLAB);
	public static final RegistryObject<Item> HIVESTONE_STAIRS = block(IterRpgModBlocks.HIVESTONE_STAIRS);
	public static final RegistryObject<Item> HIVESTONE_WALL = block(IterRpgModBlocks.HIVESTONE_WALL);
	public static final RegistryObject<Item> VOID_FRAGMENT = REGISTRY.register("void_fragment", () -> new VoidFragmentItem());
	public static final RegistryObject<Item> ELEMENTAL_INGOT = REGISTRY.register("elemental_ingot", () -> new ElementalIngotItem());
	public static final RegistryObject<Item> ELEMENTAL_FRAGMENT = REGISTRY.register("elemental_fragment", () -> new ElementalFragmentItem());
	public static final RegistryObject<Item> STARFISH = REGISTRY.register("starfish", () -> new StarfishItem());
	public static final RegistryObject<Item> SEASHELL = REGISTRY.register("seashell", () -> new SeashellItem());
	public static final RegistryObject<Item> PEARL = REGISTRY.register("pearl", () -> new PearlItem());
	public static final RegistryObject<Item> CLOUD_BLOCK = block(IterRpgModBlocks.CLOUD_BLOCK);
	public static final RegistryObject<Item> SMALL_VASE_DECO = block(IterRpgModBlocks.SMALL_VASE_DECO);
	public static final RegistryObject<Item> VASE_DECO = block(IterRpgModBlocks.VASE_DECO);
	public static final RegistryObject<Item> BIG_VASE_DECO = block(IterRpgModBlocks.BIG_VASE_DECO);
	public static final RegistryObject<Item> POTSHERD = REGISTRY.register("potsherd", () -> new PotsherdItem());
	public static final RegistryObject<Item> REVENANT_SPAWN_EGG = REGISTRY.register("revenant_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.REVENANT, -3490672, -4973520, new Item.Properties()));
	public static final RegistryObject<Item> MUDKIN_SPAWN_EGG = REGISTRY.register("mudkin_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.MUDKIN, -11060690, -11574471, new Item.Properties()));
	public static final RegistryObject<Item> HOBGOBLIN_SPAWN_EGG = REGISTRY.register("hobgoblin_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.HOBGOBLIN, -15633798, -13230801, new Item.Properties()));
	public static final RegistryObject<Item> GOBLIN_DUNGEON_GEN = block(IterRpgModBlocks.GOBLIN_DUNGEON_GEN);
	public static final RegistryObject<Item> GUNPOWDER_BARREL = block(IterRpgModBlocks.GUNPOWDER_BARREL);
	public static final RegistryObject<Item> ARTHROPOD_CATACOMBS_GEN_BLOCK = block(IterRpgModBlocks.ARTHROPOD_CATACOMBS_GEN_BLOCK);
	public static final RegistryObject<Item> PEEPER_SPAWN_EGG = REGISTRY.register("peeper_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.PEEPER, -12368305, -15592681, new Item.Properties()));
	public static final RegistryObject<Item> HOLLOW_VISAGE = REGISTRY.register("hollow_visage", () -> new HollowVisageItem());
	public static final RegistryObject<Item> DRILL = block(IterRpgModBlocks.DRILL);
	public static final RegistryObject<Item> STONE_GEODE = REGISTRY.register("stone_geode", () -> new StoneGeodeItem());
	public static final RegistryObject<Item> NETHERRACK_GEODE = REGISTRY.register("netherrack_geode", () -> new NetherrackGeodeItem());
	public static final RegistryObject<Item> BLACKSTONE_GEODE = REGISTRY.register("blackstone_geode", () -> new BlackstoneGeodeItem());
	public static final RegistryObject<Item> DEEPSLATE_GEODITE = block(IterRpgModBlocks.DEEPSLATE_GEODITE);
	public static final RegistryObject<Item> NETHERRACK_GEODITE = block(IterRpgModBlocks.NETHERRACK_GEODITE);
	public static final RegistryObject<Item> ENDSTONE_GEODITE = block(IterRpgModBlocks.ENDSTONE_GEODITE);
	public static final RegistryObject<Item> VOID_ELEMENTAL_SPAWN_EGG = REGISTRY.register("void_elemental_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.VOID_ELEMENTAL, -15462119, -34575, new Item.Properties()));
	public static final RegistryObject<Item> AIR_ELEMENTAL_SPAWN_EGG = REGISTRY.register("air_elemental_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.AIR_ELEMENTAL, -3542273, -1917878, new Item.Properties()));
	public static final RegistryObject<Item> WATER_ELEMENTAL_SPAWN_EGG = REGISTRY.register("water_elemental_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.WATER_ELEMENTAL, -9521193, -14795684, new Item.Properties()));
	public static final RegistryObject<Item> GOBLIN_SPAWN_EGG = REGISTRY.register("goblin_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.GOBLIN, -5392333, -9359322, new Item.Properties()));
	public static final RegistryObject<Item> CALTROP = REGISTRY.register("caltrop", () -> new CaltropItem());
	public static final RegistryObject<Item> SPIDER_SILK_BLOCK = block(IterRpgModBlocks.SPIDER_SILK_BLOCK);
	public static final RegistryObject<Item> INSATIABLE_SPAWN_EGG = REGISTRY.register("insatiable_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.INSATIABLE, -11107202, -11753854, new Item.Properties()));
	public static final RegistryObject<Item> AMETRINE_BRICKS = block(IterRpgModBlocks.AMETRINE_BRICKS);
	public static final RegistryObject<Item> SACRED_LOG = block(IterRpgModBlocks.SACRED_LOG);
	public static final RegistryObject<Item> SACRED_PLANKS = block(IterRpgModBlocks.SACRED_PLANKS);
	public static final RegistryObject<Item> SACRED_WOOD = block(IterRpgModBlocks.SACRED_WOOD);
	public static final RegistryObject<Item> SACRED_LEAVES = block(IterRpgModBlocks.SACRED_LEAVES);
	public static final RegistryObject<Item> SACRED_STAIRS = block(IterRpgModBlocks.SACRED_STAIRS);
	public static final RegistryObject<Item> SACRED_SLAB = block(IterRpgModBlocks.SACRED_SLAB);
	public static final RegistryObject<Item> SACRED_FENCE = block(IterRpgModBlocks.SACRED_FENCE);
	public static final RegistryObject<Item> SACRED_FENCE_GATE = block(IterRpgModBlocks.SACRED_FENCE_GATE);
	public static final RegistryObject<Item> SACRED_PRESSURE_PLATE = block(IterRpgModBlocks.SACRED_PRESSURE_PLATE);
	public static final RegistryObject<Item> SACRED_BUTTON = block(IterRpgModBlocks.SACRED_BUTTON);
	public static final RegistryObject<Item> SACRED_DOOR = doubleBlock(IterRpgModBlocks.SACRED_DOOR);
	public static final RegistryObject<Item> SACRED_TRAPDOOR = block(IterRpgModBlocks.SACRED_TRAPDOOR);
	public static final RegistryObject<Item> SACRED_TWIG = REGISTRY.register("sacred_twig", () -> new SacredTwigItem());
	public static final RegistryObject<Item> SACRED_SAPLING = block(IterRpgModBlocks.SACRED_SAPLING);
	public static final RegistryObject<Item> CRESCENT = REGISTRY.register("crescent", () -> new CrescentItem());
	public static final RegistryObject<Item> PEARL_BLOCK = block(IterRpgModBlocks.PEARL_BLOCK);
	public static final RegistryObject<Item> AMETRINE_NUGGET = REGISTRY.register("ametrine_nugget", () -> new AmetrineNuggetItem());
	public static final RegistryObject<Item> MAGMANUM_PICKAXE = REGISTRY.register("magmanum_pickaxe", () -> new MagmanumPickaxeItem());
	public static final RegistryObject<Item> GOBSTEEL_SCRAP = REGISTRY.register("gobsteel_scrap", () -> new GobsteelScrapItem());
	public static final RegistryObject<Item> MOB_PLACER = REGISTRY.register("mob_placer", () -> new MobPlacerItem());
	public static final RegistryObject<Item> GOBLIN_SPAWNER = block(IterRpgModBlocks.GOBLIN_SPAWNER);
	public static final RegistryObject<Item> ELEMENTAL_SWORD = REGISTRY.register("elemental_sword", () -> new ElementalSwordItem());
	public static final RegistryObject<Item> DEEPSLATE_GEODE = REGISTRY.register("deepslate_geode", () -> new DeepslateGeodeItem());
	public static final RegistryObject<Item> HUMIE_BUTCHER = REGISTRY.register("humie_butcher", () -> new HumieButcherItem());
	public static final RegistryObject<Item> MAGMANUM_SWORD = REGISTRY.register("magmanum_sword", () -> new MagmanumSwordItem());
	public static final RegistryObject<Item> VERY_GOOD_AND_CHEERFUL_RAPIER = REGISTRY.register("very_good_and_cheerful_rapier", () -> new VeryGoodAndCheerfulRapierItem());
	public static final RegistryObject<Item> ENDSTONE_GEODE = REGISTRY.register("endstone_geode", () -> new EndstoneGeodeItem());
	public static final RegistryObject<Item> BLOODTHIRST = REGISTRY.register("bloodthirst", () -> new BloodthirstItem());
	public static final RegistryObject<Item> EARTH_INGOT = REGISTRY.register("earth_ingot", () -> new EarthIngotItem());
	public static final RegistryObject<Item> WATER_INGOT = REGISTRY.register("water_ingot", () -> new WaterIngotItem());
	public static final RegistryObject<Item> AIR_INGOT = REGISTRY.register("air_ingot", () -> new AirIngotItem());
	public static final RegistryObject<Item> FIRE_INGOT = REGISTRY.register("fire_ingot", () -> new FireIngotItem());
	public static final RegistryObject<Item> VOID_INGOT = REGISTRY.register("void_ingot", () -> new VoidIngotItem());
	public static final RegistryObject<Item> ABYSS_QUARTZ = block(IterRpgModBlocks.ABYSS_QUARTZ);
	public static final RegistryObject<Item> ABYSSQUARTZ_SHARD = REGISTRY.register("abyssquartz_shard", () -> new AbyssquartzShardItem());
	public static final RegistryObject<Item> ABYSSQUARTZ_BLOCK = block(IterRpgModBlocks.ABYSSQUARTZ_BLOCK);
	public static final RegistryObject<Item> GRIM_SOULTRAP = block(IterRpgModBlocks.GRIM_SOULTRAP);
	public static final RegistryObject<Item> BARRIER_PROJECTOR = block(IterRpgModBlocks.BARRIER_PROJECTOR);
	public static final RegistryObject<Item> RUNIC_GRIMSTONE = block(IterRpgModBlocks.RUNIC_GRIMSTONE);
	public static final RegistryObject<Item> RUNIC_GRIMSTONE_ACTIVE = block(IterRpgModBlocks.RUNIC_GRIMSTONE_ACTIVE);
	public static final RegistryObject<Item> GIANT_PHANTOM_CHAIN = block(IterRpgModBlocks.GIANT_PHANTOM_CHAIN);
	public static final RegistryObject<Item> COIN_PILE = block(IterRpgModBlocks.COIN_PILE);
	public static final RegistryObject<Item> COIN_BLOCK = block(IterRpgModBlocks.COIN_BLOCK);
	public static final RegistryObject<Item> STINGER = REGISTRY.register("stinger", () -> new StingerItem());
	public static final RegistryObject<Item> GIANT_WEEPER_TEAR = REGISTRY.register("giant_weeper_tear", () -> new GiantWeeperTearItem());
	public static final RegistryObject<Item> MARROW = REGISTRY.register("marrow", () -> new MarrowItem());
	public static final RegistryObject<Item> SACRIFICIAL_DAGGER = REGISTRY.register("sacrificial_dagger", () -> new SacrificialDaggerItem());
	public static final RegistryObject<Item> GOBSTEEL_BLOCK = block(IterRpgModBlocks.GOBSTEEL_BLOCK);
	public static final RegistryObject<Item> FIEND_SPAWN_EGG = REGISTRY.register("fiend_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.FIEND, -4379085, -3490672, new Item.Properties()));
	public static final RegistryObject<Item> CARCASS_SPAWN_EGG = REGISTRY.register("carcass_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.CARCASS, -3490672, -2279376, new Item.Properties()));
	public static final RegistryObject<Item> PROFANE_FLESH = REGISTRY.register("profane_flesh", () -> new ProfaneFleshItem());
	public static final RegistryObject<Item> HARVEST = REGISTRY.register("harvest", () -> new HarvestItem());
	public static final RegistryObject<Item> ETERNAL_TORRENT = REGISTRY.register("eternal_torrent", () -> new EternalTorrentItem());
	public static final RegistryObject<Item> STORMCALLER = REGISTRY.register("stormcaller", () -> new StormcallerItem());
	public static final RegistryObject<Item> SOLSTICE = REGISTRY.register("solstice", () -> new SolsticeItem());
	public static final RegistryObject<Item> STARLESSNESS = REGISTRY.register("starlessness", () -> new StarlessnessItem());
	public static final RegistryObject<Item> PROFANE_FLESH_BLOCK = block(IterRpgModBlocks.PROFANE_FLESH_BLOCK);
	public static final RegistryObject<Item> CALIBRATED_LENS = REGISTRY.register("calibrated_lens", () -> new CalibratedLensItem());
	public static final RegistryObject<Item> DEMONBONES = block(IterRpgModBlocks.DEMONBONES);
	public static final RegistryObject<Item> SPELL_BOOK = REGISTRY.register("spell_book", () -> new SpellBookItem());
	public static final RegistryObject<Item> AMETRINE_PENDANT = REGISTRY.register("ametrine_pendant", () -> new AmetrinePendantItem());
	public static final RegistryObject<Item> DWARF_SPAWN_EGG = REGISTRY.register("dwarf_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.DWARF, -8098460, -5353678, new Item.Properties()));
	public static final RegistryObject<Item> MUG = REGISTRY.register("mug", () -> new MugItem());
	public static final RegistryObject<Item> BEER_MUG = REGISTRY.register("beer_mug", () -> new BeerMugItem());
	public static final RegistryObject<Item> SPIDER_MEAD_MUG = REGISTRY.register("spider_mead_mug", () -> new SpiderMeadMugItem());
	public static final RegistryObject<Item> DRIFTBOW = REGISTRY.register("driftbow", () -> new DriftbowItem());
	public static final RegistryObject<Item> ABYSSQUARTZ_CAPACITATOR = REGISTRY.register("abyssquartz_capacitator", () -> new AbyssquartzCapacitatorItem());
	public static final RegistryObject<Item> SPELL_HEAL = REGISTRY.register("spell_heal", () -> new SpellHealItem());
	public static final RegistryObject<Item> AMETHYST_WAND = REGISTRY.register("amethyst_wand", () -> new AmethystWandItem());
	public static final RegistryObject<Item> RAGGED_HELMET = REGISTRY.register("ragged_helmet", () -> new RaggedItem.Helmet());
	public static final RegistryObject<Item> RAGGED_CHESTPLATE = REGISTRY.register("ragged_chestplate", () -> new RaggedItem.Chestplate());
	public static final RegistryObject<Item> RAGGED_LEGGINGS = REGISTRY.register("ragged_leggings", () -> new RaggedItem.Leggings());
	public static final RegistryObject<Item> RAGGED_BOOTS = REGISTRY.register("ragged_boots", () -> new RaggedItem.Boots());
	public static final RegistryObject<Item> ELEMENTAL_UPGRADE = REGISTRY.register("elemental_upgrade", () -> new ElementalUpgradeItem());
	public static final RegistryObject<Item> WOODEN_SPEAR = REGISTRY.register("wooden_spear", () -> new WoodenSpearItem());
	public static final RegistryObject<Item> STONE_SPEAR = REGISTRY.register("stone_spear", () -> new StoneSpearItem());
	public static final RegistryObject<Item> IRON_SPEAR = REGISTRY.register("iron_spear", () -> new IronSpearItem());
	public static final RegistryObject<Item> GOLDEN_SPEAR = REGISTRY.register("golden_spear", () -> new GoldenSpearItem());
	public static final RegistryObject<Item> DIAMOND_SPEAR = REGISTRY.register("diamond_spear", () -> new DiamondSpearItem());
	public static final RegistryObject<Item> NETHERITE_SPEAR = REGISTRY.register("netherite_spear", () -> new NetheriteSpearItem());
	public static final RegistryObject<Item> WODDEN_DAGGER = REGISTRY.register("wodden_dagger", () -> new WoddenDaggerItem());
	public static final RegistryObject<Item> STONE_DAGGER = REGISTRY.register("stone_dagger", () -> new StoneDaggerItem());
	public static final RegistryObject<Item> IRON_DAGGER = REGISTRY.register("iron_dagger", () -> new IronDaggerItem());
	public static final RegistryObject<Item> GOLDEN_DAGGER = REGISTRY.register("golden_dagger", () -> new GoldenDaggerItem());
	public static final RegistryObject<Item> DIAMOND_DAGGER = REGISTRY.register("diamond_dagger", () -> new DiamondDaggerItem());
	public static final RegistryObject<Item> NETHERITE_DAGGER = REGISTRY.register("netherite_dagger", () -> new NetheriteDaggerItem());
	public static final RegistryObject<Item> MONOLITH_STONE = block(IterRpgModBlocks.MONOLITH_STONE);
	public static final RegistryObject<Item> EARTH_SEAL = block(IterRpgModBlocks.EARTH_SEAL);
	public static final RegistryObject<Item> WATER_SEAL = block(IterRpgModBlocks.WATER_SEAL);
	public static final RegistryObject<Item> AIR_SEAL = block(IterRpgModBlocks.AIR_SEAL);
	public static final RegistryObject<Item> FIRE_SEAL = block(IterRpgModBlocks.FIRE_SEAL);
	public static final RegistryObject<Item> VOID_SEAL = block(IterRpgModBlocks.VOID_SEAL);
	public static final RegistryObject<Item> MONOLITH_STAIRS = block(IterRpgModBlocks.MONOLITH_STAIRS);
	public static final RegistryObject<Item> MONOLITH_SLAB = block(IterRpgModBlocks.MONOLITH_SLAB);
	public static final RegistryObject<Item> MONOLITH_WALL = block(IterRpgModBlocks.MONOLITH_WALL);
	public static final RegistryObject<Item> SPIRE_SPAWNER = block(IterRpgModBlocks.SPIRE_SPAWNER);
	public static final RegistryObject<Item> GRAND_SPIRE_SPAWNER = block(IterRpgModBlocks.GRAND_SPIRE_SPAWNER);
	public static final RegistryObject<Item> AMETRINE_HELMET = REGISTRY.register("ametrine_helmet", () -> new AmetrineItem.Helmet());
	public static final RegistryObject<Item> AMETRINE_CHESTPLATE = REGISTRY.register("ametrine_chestplate", () -> new AmetrineItem.Chestplate());
	public static final RegistryObject<Item> AMETRINE_LEGGINGS = REGISTRY.register("ametrine_leggings", () -> new AmetrineItem.Leggings());
	public static final RegistryObject<Item> AMETRINE_BOOTS = REGISTRY.register("ametrine_boots", () -> new AmetrineItem.Boots());
	public static final RegistryObject<Item> AMETRINE_SWORD = REGISTRY.register("ametrine_sword", () -> new AmetrineSwordItem());
	public static final RegistryObject<Item> AMETRINE_PICKAXE = REGISTRY.register("ametrine_pickaxe", () -> new AmetrinePickaxeItem());
	public static final RegistryObject<Item> AMETRINE_AXE = REGISTRY.register("ametrine_axe", () -> new AmetrineAxeItem());
	public static final RegistryObject<Item> AMETRINE_SHOVEL = REGISTRY.register("ametrine_shovel", () -> new AmetrineShovelItem());
	public static final RegistryObject<Item> AMETRINE_HOE = REGISTRY.register("ametrine_hoe", () -> new AmetrineHoeItem());
	public static final RegistryObject<Item> AMETRINE_DAGGER = REGISTRY.register("ametrine_dagger", () -> new AmetrineDaggerItem());
	public static final RegistryObject<Item> AMETRINE_SPEAR = REGISTRY.register("ametrine_spear", () -> new AmetrineSpearItem());
	public static final RegistryObject<Item> AMETRINE_SCYTHE = REGISTRY.register("ametrine_scythe", () -> new AmetrineScytheItem());
	public static final RegistryObject<Item> AMETRINE_FLAIL = REGISTRY.register("ametrine_flail", () -> new AmetrineFlailItem());
	public static final RegistryObject<Item> ESSENCE_OF_CREATION = REGISTRY.register("essence_of_creation", () -> new EssenceOfCreationItem());
	public static final RegistryObject<Item> SPELL_IGNITE = REGISTRY.register("spell_ignite", () -> new SpellIgniteItem());
	public static final RegistryObject<Item> SCAB_SPAWN_EGG = REGISTRY.register("scab_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.SCAB, -52429, -2178172, new Item.Properties()));
	public static final RegistryObject<Item> SPELL_GUST = REGISTRY.register("spell_gust", () -> new SpellGustItem());
	public static final RegistryObject<Item> SPELL_SPLASHES = REGISTRY.register("spell_splashes", () -> new SpellSplashesItem());
	public static final RegistryObject<Item> BOTTLE_OF_OBSIDIAN_TEARS = REGISTRY.register("bottle_of_obsidian_tears", () -> new BottleOfObsidianTearsItem());
	public static final RegistryObject<Item> BONB = REGISTRY.register("bonb", () -> new BonbItem());
	public static final RegistryObject<Item> TENDONS_BLOCK = block(IterRpgModBlocks.TENDONS_BLOCK);
	public static final RegistryObject<Item> GOBSTEEL_JAVELIN = REGISTRY.register("gobsteel_javelin", () -> new GobsteelJavelinItem());
	public static final RegistryObject<Item> SPELL_CULTIVATE = REGISTRY.register("spell_cultivate", () -> new SpellCultivateItem());
	public static final RegistryObject<Item> SPELL_ATTRACT = REGISTRY.register("spell_attract", () -> new SpellAttractItem());
	public static final RegistryObject<Item> VILE_TISSUE = REGISTRY.register("vile_tissue", () -> new VileTissueItem());
	public static final RegistryObject<Item> DEMONBONE_FRAGMENTS = REGISTRY.register("demonbone_fragments", () -> new DemonboneFragmentsItem());
	public static final RegistryObject<Item> GRIMACE_TRAP = block(IterRpgModBlocks.GRIMACE_TRAP);
	public static final RegistryObject<Item> TEAR_CATCHER = block(IterRpgModBlocks.TEAR_CATCHER);
	public static final RegistryObject<Item> ETHERBLOOM_DECOCTION = REGISTRY.register("etherbloom_decoction", () -> new EtherbloomDecoctionItem());
	public static final RegistryObject<Item> GRIM_LOCKER = block(IterRpgModBlocks.GRIM_LOCKER);
	public static final RegistryObject<Item> SMALL_SCALLOP_SPAWN_EGG = REGISTRY.register("small_scallop_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.SMALL_SCALLOP, -10134683, -2706222, new Item.Properties()));
	public static final RegistryObject<Item> STRIPPED_SACRED_LOG = block(IterRpgModBlocks.STRIPPED_SACRED_LOG);
	public static final RegistryObject<Item> DEEPSTEEL_INGOT = REGISTRY.register("deepsteel_ingot", () -> new DeepsteelIngotItem());
	public static final RegistryObject<Item> DEEPSTEEL_SWORD = REGISTRY.register("deepsteel_sword", () -> new DeepsteelSwordItem());
	public static final RegistryObject<Item> DEEPSTEEL_PICKAXE = REGISTRY.register("deepsteel_pickaxe", () -> new DeepsteelPickaxeItem());
	public static final RegistryObject<Item> VOID_MAW = block(IterRpgModBlocks.VOID_MAW);
	public static final RegistryObject<Item> UNIDENTIFIED_SPELL = REGISTRY.register("unidentified_spell", () -> new UnidentifiedSpellItem());
	public static final RegistryObject<Item> WARPED_GOO = REGISTRY.register("warped_goo", () -> new WarpedGooItem());
	public static final RegistryObject<Item> ARCANIST_TABLE = block(IterRpgModBlocks.ARCANIST_TABLE);
	public static final RegistryObject<Item> SPELL_ETHERBOLT = REGISTRY.register("spell_etherbolt", () -> new SpellEtherboltItem());
	public static final RegistryObject<Item> SPELL_ETHERBLAST = REGISTRY.register("spell_etherblast", () -> new SpellEtherblastItem());
	public static final RegistryObject<Item> ABSTRUSE_CLOTH = REGISTRY.register("abstruse_cloth", () -> new AbstruseClothItem());
	public static final RegistryObject<Item> GIST = REGISTRY.register("gist", () -> new GistItem());
	public static final RegistryObject<Item> HALFLOWER = block(IterRpgModBlocks.HALFLOWER);
	public static final RegistryObject<Item> UNBOUND_SOUL_SPAWN_EGG = REGISTRY.register("unbound_soul_spawn_egg", () -> new ForgeSpawnEggItem(IterRpgModEntities.UNBOUND_SOUL, -7231558, -10127481, new Item.Properties()));
	public static final RegistryObject<Item> TOMBSTONE = block(IterRpgModBlocks.TOMBSTONE);
	public static final RegistryObject<Item> TOMBSTONE_FRAGMENT = REGISTRY.register("tombstone_fragment", () -> new TombstoneFragmentItem());
	public static final RegistryObject<Item> HAUNTED_SPLINTER = REGISTRY.register("haunted_splinter", () -> new HauntedSplinterItem());
	public static final RegistryObject<Item> ELEMENTAL_ARMOR_HELMET = REGISTRY.register("elemental_armor_helmet", () -> new ElementalArmorItem.Helmet());
	public static final RegistryObject<Item> ELEMENTAL_ARMOR_CHESTPLATE = REGISTRY.register("elemental_armor_chestplate", () -> new ElementalArmorItem.Chestplate());
	public static final RegistryObject<Item> ELEMENTAL_ARMOR_LEGGINGS = REGISTRY.register("elemental_armor_leggings", () -> new ElementalArmorItem.Leggings());
	public static final RegistryObject<Item> ELEMENTAL_ARMOR_BOOTS = REGISTRY.register("elemental_armor_boots", () -> new ElementalArmorItem.Boots());
	public static final RegistryObject<Item> GRAVE_CROSS = block(IterRpgModBlocks.GRAVE_CROSS);
	public static final RegistryObject<Item> ECTOPLASM = REGISTRY.register("ectoplasm", () -> new EctoplasmItem());
	public static final RegistryObject<Item> OTHERWORDLY_INGOT = REGISTRY.register("otherwordly_ingot", () -> new OtherwordlyIngotItem());
	public static final RegistryObject<Item> COIN_POUCH = REGISTRY.register("coin_pouch", () -> new CoinPouchItem());
	public static final RegistryObject<Item> SPELL_EMBERS = REGISTRY.register("spell_embers", () -> new SpellEmbersItem());
	public static final RegistryObject<Item> SPELL_DROPLETS = REGISTRY.register("spell_droplets", () -> new SpellDropletsItem());
	public static final RegistryObject<Item> SPELL_ZAP = REGISTRY.register("spell_zap", () -> new SpellZapItem());

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}

	private static RegistryObject<Item> doubleBlock(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new DoubleHighBlockItem(block.get(), new Item.Properties()));
	}

	@SubscribeEvent
	public static void clientLoad(FMLClientSetupEvent event) {
		event.enqueueWork(() -> {
			ItemProperties.register(BLOODBRANCH.get(), new ResourceLocation("iter_rpg:bloodbranch_pulling"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) BloodbranchProvideValueProcedure.execute(entity, itemStackToRender));
		});
	}
}
